/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AporteSolicitud,
  ConflictoResponse,
  CuotaPrestamoSolicitud,
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  OperacionRegistrada,
  PrecondicionRequeridaResponse,
  PrestamoSolicitud,
  ProhibidoResponse,
  SolicitudInvalidaResponse,
  TrasladoSolicitud,
  VistaPreviaOperacion
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type registrarAporteResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarAporteResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarAporteResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarAporteResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarAporteResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarAporteResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarAporteResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarAporteResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarAporteResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarAporteResponseSuccess = (registrarAporteResponse201) & {
  headers: Headers;
};
export type registrarAporteResponseError = (registrarAporteResponse400 | registrarAporteResponse401 | registrarAporteResponse403 | registrarAporteResponse409 | registrarAporteResponse422 | registrarAporteResponse428 | registrarAporteResponse429 | registrarAporteResponse500) & {
  headers: Headers;
};

export type registrarAporteResponse = (registrarAporteResponseSuccess | registrarAporteResponseError)

export const getRegistrarAporteUrl = () => {




  return `/contabilidad/operaciones/aportes`
}

/**
 * Registra un aporte de capital, acreditando la cuenta de capital (ADR-041 §5.3), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra un aporte de capital
 */
export const registrarAporte = async (aporteSolicitud: AporteSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarAporteResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarAporteResponse>(getRegistrarAporteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(aporteSolicitud)
  }
);}





export const getRegistrarAporteQueryKey = (aporteSolicitud?: AporteSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/aportes`, aporteSolicitud
    ] as const;
    }


export const getRegistrarAporteQueryOptions = <TData = Awaited<ReturnType<typeof registrarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAporte>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarAporteQueryKey(aporteSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarAporte>>> = ({ signal }) => registrarAporte(aporteSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarAporte>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarAporteQueryResult = NonNullable<Awaited<ReturnType<typeof registrarAporte>>>
export type RegistrarAporteQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarAporte<TData = Awaited<ReturnType<typeof registrarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAporte>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarAporte>>,
          TError,
          Awaited<ReturnType<typeof registrarAporte>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarAporte<TData = Awaited<ReturnType<typeof registrarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAporte>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarAporte>>,
          TError,
          Awaited<ReturnType<typeof registrarAporte>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarAporte<TData = Awaited<ReturnType<typeof registrarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAporte>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra un aporte de capital
 */

export function useRegistrarAporte<TData = Awaited<ReturnType<typeof registrarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAporte>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarAporteQueryOptions(aporteSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarAporteResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarAporteResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarAporteResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarAporteResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarAporteResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarAporteResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarAporteResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarAporteResponseSuccess = (previsualizarAporteResponse200) & {
  headers: Headers;
};
export type previsualizarAporteResponseError = (previsualizarAporteResponse400 | previsualizarAporteResponse401 | previsualizarAporteResponse403 | previsualizarAporteResponse422 | previsualizarAporteResponse429 | previsualizarAporteResponse500) & {
  headers: Headers;
};

export type previsualizarAporteResponse = (previsualizarAporteResponseSuccess | previsualizarAporteResponseError)

export const getPrevisualizarAporteUrl = () => {




  return `/contabilidad/operaciones/aportes/vista-previa`
}

/**
 * Arma el asiento de un aporte de capital y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de un aporte de capital sin guardarlo
 */
export const previsualizarAporte = async (aporteSolicitud: AporteSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarAporteResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarAporteResponse>(getPrevisualizarAporteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(aporteSolicitud)
  }
);}





export const getPrevisualizarAporteQueryKey = (aporteSolicitud?: AporteSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/aportes/vista-previa`, aporteSolicitud
    ] as const;
    }


export const getPrevisualizarAporteQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAporte>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarAporteQueryKey(aporteSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarAporte>>> = ({ signal }) => previsualizarAporte(aporteSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarAporte>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarAporteQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarAporte>>>
export type PrevisualizarAporteQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarAporte<TData = Awaited<ReturnType<typeof previsualizarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAporte>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarAporte>>,
          TError,
          Awaited<ReturnType<typeof previsualizarAporte>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarAporte<TData = Awaited<ReturnType<typeof previsualizarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAporte>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarAporte>>,
          TError,
          Awaited<ReturnType<typeof previsualizarAporte>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarAporte<TData = Awaited<ReturnType<typeof previsualizarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAporte>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de un aporte de capital sin guardarlo
 */

export function usePrevisualizarAporte<TData = Awaited<ReturnType<typeof previsualizarAporte>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 aporteSolicitud: AporteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAporte>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarAporteQueryOptions(aporteSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registrarPrestamoResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarPrestamoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarPrestamoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarPrestamoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarPrestamoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarPrestamoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarPrestamoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarPrestamoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarPrestamoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarPrestamoResponseSuccess = (registrarPrestamoResponse201) & {
  headers: Headers;
};
export type registrarPrestamoResponseError = (registrarPrestamoResponse400 | registrarPrestamoResponse401 | registrarPrestamoResponse403 | registrarPrestamoResponse409 | registrarPrestamoResponse422 | registrarPrestamoResponse428 | registrarPrestamoResponse429 | registrarPrestamoResponse500) & {
  headers: Headers;
};

export type registrarPrestamoResponse = (registrarPrestamoResponseSuccess | registrarPrestamoResponseError)

export const getRegistrarPrestamoUrl = () => {




  return `/contabilidad/operaciones/prestamos`
}

/**
 * Registra un préstamo recibido, acreditando el pasivo de corto o de largo plazo según el plazo (ADR-041 §5.3), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra un préstamo recibido
 */
export const registrarPrestamo = async (prestamoSolicitud: PrestamoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarPrestamoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarPrestamoResponse>(getRegistrarPrestamoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(prestamoSolicitud)
  }
);}





export const getRegistrarPrestamoQueryKey = (prestamoSolicitud?: PrestamoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/prestamos`, prestamoSolicitud
    ] as const;
    }


export const getRegistrarPrestamoQueryOptions = <TData = Awaited<ReturnType<typeof registrarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarPrestamoQueryKey(prestamoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarPrestamo>>> = ({ signal }) => registrarPrestamo(prestamoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarPrestamo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarPrestamoQueryResult = NonNullable<Awaited<ReturnType<typeof registrarPrestamo>>>
export type RegistrarPrestamoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarPrestamo<TData = Awaited<ReturnType<typeof registrarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPrestamo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarPrestamo>>,
          TError,
          Awaited<ReturnType<typeof registrarPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarPrestamo<TData = Awaited<ReturnType<typeof registrarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPrestamo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarPrestamo>>,
          TError,
          Awaited<ReturnType<typeof registrarPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarPrestamo<TData = Awaited<ReturnType<typeof registrarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra un préstamo recibido
 */

export function useRegistrarPrestamo<TData = Awaited<ReturnType<typeof registrarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarPrestamoQueryOptions(prestamoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarPrestamoResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarPrestamoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarPrestamoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarPrestamoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarPrestamoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarPrestamoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarPrestamoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarPrestamoResponseSuccess = (previsualizarPrestamoResponse200) & {
  headers: Headers;
};
export type previsualizarPrestamoResponseError = (previsualizarPrestamoResponse400 | previsualizarPrestamoResponse401 | previsualizarPrestamoResponse403 | previsualizarPrestamoResponse422 | previsualizarPrestamoResponse429 | previsualizarPrestamoResponse500) & {
  headers: Headers;
};

export type previsualizarPrestamoResponse = (previsualizarPrestamoResponseSuccess | previsualizarPrestamoResponseError)

export const getPrevisualizarPrestamoUrl = () => {




  return `/contabilidad/operaciones/prestamos/vista-previa`
}

/**
 * Arma el asiento de un préstamo recibido y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de un préstamo recibido sin guardarlo
 */
export const previsualizarPrestamo = async (prestamoSolicitud: PrestamoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarPrestamoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarPrestamoResponse>(getPrevisualizarPrestamoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(prestamoSolicitud)
  }
);}





export const getPrevisualizarPrestamoQueryKey = (prestamoSolicitud?: PrestamoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/prestamos/vista-previa`, prestamoSolicitud
    ] as const;
    }


export const getPrevisualizarPrestamoQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarPrestamoQueryKey(prestamoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarPrestamo>>> = ({ signal }) => previsualizarPrestamo(prestamoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarPrestamo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarPrestamoQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarPrestamo>>>
export type PrevisualizarPrestamoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarPrestamo<TData = Awaited<ReturnType<typeof previsualizarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPrestamo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarPrestamo>>,
          TError,
          Awaited<ReturnType<typeof previsualizarPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarPrestamo<TData = Awaited<ReturnType<typeof previsualizarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPrestamo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarPrestamo>>,
          TError,
          Awaited<ReturnType<typeof previsualizarPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarPrestamo<TData = Awaited<ReturnType<typeof previsualizarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de un préstamo recibido sin guardarlo
 */

export function usePrevisualizarPrestamo<TData = Awaited<ReturnType<typeof previsualizarPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 prestamoSolicitud: PrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarPrestamoQueryOptions(prestamoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registrarCuotaPrestamoResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarCuotaPrestamoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarCuotaPrestamoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarCuotaPrestamoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarCuotaPrestamoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarCuotaPrestamoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarCuotaPrestamoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarCuotaPrestamoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarCuotaPrestamoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarCuotaPrestamoResponseSuccess = (registrarCuotaPrestamoResponse201) & {
  headers: Headers;
};
export type registrarCuotaPrestamoResponseError = (registrarCuotaPrestamoResponse400 | registrarCuotaPrestamoResponse401 | registrarCuotaPrestamoResponse403 | registrarCuotaPrestamoResponse409 | registrarCuotaPrestamoResponse422 | registrarCuotaPrestamoResponse428 | registrarCuotaPrestamoResponse429 | registrarCuotaPrestamoResponse500) & {
  headers: Headers;
};

export type registrarCuotaPrestamoResponse = (registrarCuotaPrestamoResponseSuccess | registrarCuotaPrestamoResponseError)

export const getRegistrarCuotaPrestamoUrl = () => {




  return `/contabilidad/operaciones/cuotas-prestamo`
}

/**
 * Registra el pago de una cuota de préstamo, separando capital, intereses y comisión (ADR-041 §5.3), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra el pago de una cuota de préstamo
 */
export const registrarCuotaPrestamo = async (cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarCuotaPrestamoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarCuotaPrestamoResponse>(getRegistrarCuotaPrestamoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cuotaPrestamoSolicitud)
  }
);}





export const getRegistrarCuotaPrestamoQueryKey = (cuotaPrestamoSolicitud?: CuotaPrestamoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/cuotas-prestamo`, cuotaPrestamoSolicitud
    ] as const;
    }


export const getRegistrarCuotaPrestamoQueryOptions = <TData = Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarCuotaPrestamoQueryKey(cuotaPrestamoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarCuotaPrestamo>>> = ({ signal }) => registrarCuotaPrestamo(cuotaPrestamoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarCuotaPrestamoQueryResult = NonNullable<Awaited<ReturnType<typeof registrarCuotaPrestamo>>>
export type RegistrarCuotaPrestamoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarCuotaPrestamo<TData = Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarCuotaPrestamo>>,
          TError,
          Awaited<ReturnType<typeof registrarCuotaPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarCuotaPrestamo<TData = Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarCuotaPrestamo>>,
          TError,
          Awaited<ReturnType<typeof registrarCuotaPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarCuotaPrestamo<TData = Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra el pago de una cuota de préstamo
 */

export function useRegistrarCuotaPrestamo<TData = Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCuotaPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarCuotaPrestamoQueryOptions(cuotaPrestamoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarCuotaPrestamoResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarCuotaPrestamoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarCuotaPrestamoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarCuotaPrestamoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarCuotaPrestamoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarCuotaPrestamoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarCuotaPrestamoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarCuotaPrestamoResponseSuccess = (previsualizarCuotaPrestamoResponse200) & {
  headers: Headers;
};
export type previsualizarCuotaPrestamoResponseError = (previsualizarCuotaPrestamoResponse400 | previsualizarCuotaPrestamoResponse401 | previsualizarCuotaPrestamoResponse403 | previsualizarCuotaPrestamoResponse422 | previsualizarCuotaPrestamoResponse429 | previsualizarCuotaPrestamoResponse500) & {
  headers: Headers;
};

export type previsualizarCuotaPrestamoResponse = (previsualizarCuotaPrestamoResponseSuccess | previsualizarCuotaPrestamoResponseError)

export const getPrevisualizarCuotaPrestamoUrl = () => {




  return `/contabilidad/operaciones/cuotas-prestamo/vista-previa`
}

/**
 * Arma el asiento de una cuota de préstamo y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa del pago de una cuota de préstamo sin guardarlo
 */
export const previsualizarCuotaPrestamo = async (cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarCuotaPrestamoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarCuotaPrestamoResponse>(getPrevisualizarCuotaPrestamoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cuotaPrestamoSolicitud)
  }
);}





export const getPrevisualizarCuotaPrestamoQueryKey = (cuotaPrestamoSolicitud?: CuotaPrestamoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/cuotas-prestamo/vista-previa`, cuotaPrestamoSolicitud
    ] as const;
    }


export const getPrevisualizarCuotaPrestamoQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarCuotaPrestamoQueryKey(cuotaPrestamoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>> = ({ signal }) => previsualizarCuotaPrestamo(cuotaPrestamoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarCuotaPrestamoQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>>
export type PrevisualizarCuotaPrestamoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarCuotaPrestamo<TData = Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>,
          TError,
          Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarCuotaPrestamo<TData = Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>,
          TError,
          Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarCuotaPrestamo<TData = Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa del pago de una cuota de préstamo sin guardarlo
 */

export function usePrevisualizarCuotaPrestamo<TData = Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cuotaPrestamoSolicitud: CuotaPrestamoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCuotaPrestamo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarCuotaPrestamoQueryOptions(cuotaPrestamoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registrarTrasladoResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarTrasladoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarTrasladoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarTrasladoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarTrasladoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarTrasladoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarTrasladoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarTrasladoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarTrasladoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarTrasladoResponseSuccess = (registrarTrasladoResponse201) & {
  headers: Headers;
};
export type registrarTrasladoResponseError = (registrarTrasladoResponse400 | registrarTrasladoResponse401 | registrarTrasladoResponse403 | registrarTrasladoResponse409 | registrarTrasladoResponse422 | registrarTrasladoResponse428 | registrarTrasladoResponse429 | registrarTrasladoResponse500) & {
  headers: Headers;
};

export type registrarTrasladoResponse = (registrarTrasladoResponseSuccess | registrarTrasladoResponseError)

export const getRegistrarTrasladoUrl = () => {




  return `/contabilidad/operaciones/traslados`
}

/**
 * Registra un traslado entre dos cuentas de efectivo o bancos del grupo 1101 (ADR-041 §5.3), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra un traslado de fondos
 */
export const registrarTraslado = async (trasladoSolicitud: TrasladoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarTrasladoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarTrasladoResponse>(getRegistrarTrasladoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(trasladoSolicitud)
  }
);}





export const getRegistrarTrasladoQueryKey = (trasladoSolicitud?: TrasladoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/traslados`, trasladoSolicitud
    ] as const;
    }


export const getRegistrarTrasladoQueryOptions = <TData = Awaited<ReturnType<typeof registrarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarTraslado>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarTrasladoQueryKey(trasladoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarTraslado>>> = ({ signal }) => registrarTraslado(trasladoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarTraslado>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarTrasladoQueryResult = NonNullable<Awaited<ReturnType<typeof registrarTraslado>>>
export type RegistrarTrasladoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarTraslado<TData = Awaited<ReturnType<typeof registrarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarTraslado>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarTraslado>>,
          TError,
          Awaited<ReturnType<typeof registrarTraslado>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarTraslado<TData = Awaited<ReturnType<typeof registrarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarTraslado>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarTraslado>>,
          TError,
          Awaited<ReturnType<typeof registrarTraslado>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarTraslado<TData = Awaited<ReturnType<typeof registrarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarTraslado>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra un traslado de fondos
 */

export function useRegistrarTraslado<TData = Awaited<ReturnType<typeof registrarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarTraslado>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarTrasladoQueryOptions(trasladoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarTrasladoResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarTrasladoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarTrasladoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarTrasladoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarTrasladoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarTrasladoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarTrasladoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarTrasladoResponseSuccess = (previsualizarTrasladoResponse200) & {
  headers: Headers;
};
export type previsualizarTrasladoResponseError = (previsualizarTrasladoResponse400 | previsualizarTrasladoResponse401 | previsualizarTrasladoResponse403 | previsualizarTrasladoResponse422 | previsualizarTrasladoResponse429 | previsualizarTrasladoResponse500) & {
  headers: Headers;
};

export type previsualizarTrasladoResponse = (previsualizarTrasladoResponseSuccess | previsualizarTrasladoResponseError)

export const getPrevisualizarTrasladoUrl = () => {




  return `/contabilidad/operaciones/traslados/vista-previa`
}

/**
 * Arma el asiento de un traslado de fondos y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de un traslado de fondos sin guardarlo
 */
export const previsualizarTraslado = async (trasladoSolicitud: TrasladoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarTrasladoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarTrasladoResponse>(getPrevisualizarTrasladoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(trasladoSolicitud)
  }
);}





export const getPrevisualizarTrasladoQueryKey = (trasladoSolicitud?: TrasladoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/traslados/vista-previa`, trasladoSolicitud
    ] as const;
    }


export const getPrevisualizarTrasladoQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarTraslado>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarTrasladoQueryKey(trasladoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarTraslado>>> = ({ signal }) => previsualizarTraslado(trasladoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarTraslado>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarTrasladoQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarTraslado>>>
export type PrevisualizarTrasladoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarTraslado<TData = Awaited<ReturnType<typeof previsualizarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarTraslado>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarTraslado>>,
          TError,
          Awaited<ReturnType<typeof previsualizarTraslado>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarTraslado<TData = Awaited<ReturnType<typeof previsualizarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarTraslado>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarTraslado>>,
          TError,
          Awaited<ReturnType<typeof previsualizarTraslado>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarTraslado<TData = Awaited<ReturnType<typeof previsualizarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarTraslado>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de un traslado de fondos sin guardarlo
 */

export function usePrevisualizarTraslado<TData = Awaited<ReturnType<typeof previsualizarTraslado>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 trasladoSolicitud: TrasladoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarTraslado>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarTrasladoQueryOptions(trasladoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






