/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActualizacionReglaContabilizacion,
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  ListarReglasContabilizacionParams,
  NoAutenticadoResponse,
  NoEncontradoResponse,
  PrecondicionFallidaResponse,
  PrecondicionRequeridaResponse,
  ProhibidoResponse,
  ReglaContabilizacion,
  SolicitudInvalidaResponse
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listarReglasContabilizacionResponse200 = {
  data: ReglaContabilizacion[]
  status: 200
}

export type listarReglasContabilizacionResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type listarReglasContabilizacionResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type listarReglasContabilizacionResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type listarReglasContabilizacionResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type listarReglasContabilizacionResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type listarReglasContabilizacionResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type listarReglasContabilizacionResponseSuccess = (listarReglasContabilizacionResponse200) & {
  headers: Headers;
};
export type listarReglasContabilizacionResponseError = (listarReglasContabilizacionResponse400 | listarReglasContabilizacionResponse401 | listarReglasContabilizacionResponse403 | listarReglasContabilizacionResponse422 | listarReglasContabilizacionResponse429 | listarReglasContabilizacionResponse500) & {
  headers: Headers;
};

export type listarReglasContabilizacionResponse = (listarReglasContabilizacionResponseSuccess | listarReglasContabilizacionResponseError)

export const getListarReglasContabilizacionUrl = (params?: ListarReglasContabilizacionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/reglas-contabilizacion?${stringifiedParams}` : `/contabilidad/reglas-contabilizacion`
}

/**
 * Devuelve las reglas de contabilización de la empresa, sin paginar, ordenadas por tipo de operación, categoría y código. El filtro tipoOperacion es opcional. Cada regla trae su version, que es el valor que se envía entre comillas como If-Match al editarla. Rol mínimo: auditor.
 * @summary Lista las reglas de contabilización
 */
export const listarReglasContabilizacion = async (params?: ListarReglasContabilizacionParams, options?: Parameters<typeof clienteHttp>[1]): Promise<listarReglasContabilizacionResponse> => {

  return clienteHttp<listarReglasContabilizacionResponse>(getListarReglasContabilizacionUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarReglasContabilizacionQueryKey = (params?: ListarReglasContabilizacionParams,) => {
    return [
    `/contabilidad/reglas-contabilizacion`, ...(params ? [params] : [])
    ] as const;
    }


export const getListarReglasContabilizacionQueryOptions = <TData = Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params?: ListarReglasContabilizacionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarReglasContabilizacionQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarReglasContabilizacion>>> = ({ signal }) => listarReglasContabilizacion(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarReglasContabilizacionQueryResult = NonNullable<Awaited<ReturnType<typeof listarReglasContabilizacion>>>
export type ListarReglasContabilizacionQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useListarReglasContabilizacion<TData = Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: undefined |  ListarReglasContabilizacionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarReglasContabilizacion>>,
          TError,
          Awaited<ReturnType<typeof listarReglasContabilizacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarReglasContabilizacion<TData = Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarReglasContabilizacionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarReglasContabilizacion>>,
          TError,
          Awaited<ReturnType<typeof listarReglasContabilizacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarReglasContabilizacion<TData = Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarReglasContabilizacionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista las reglas de contabilización
 */

export function useListarReglasContabilizacion<TData = Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarReglasContabilizacionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarReglasContabilizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarReglasContabilizacionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type actualizarReglaContabilizacionResponse200 = {
  data: ReglaContabilizacion
  status: 200
}

export type actualizarReglaContabilizacionResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type actualizarReglaContabilizacionResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type actualizarReglaContabilizacionResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type actualizarReglaContabilizacionResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type actualizarReglaContabilizacionResponse412 = {
  data: PrecondicionFallidaResponse
  status: 412
}

export type actualizarReglaContabilizacionResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type actualizarReglaContabilizacionResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type actualizarReglaContabilizacionResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type actualizarReglaContabilizacionResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type actualizarReglaContabilizacionResponseSuccess = (actualizarReglaContabilizacionResponse200) & {
  headers: Headers;
};
export type actualizarReglaContabilizacionResponseError = (actualizarReglaContabilizacionResponse400 | actualizarReglaContabilizacionResponse401 | actualizarReglaContabilizacionResponse403 | actualizarReglaContabilizacionResponse404 | actualizarReglaContabilizacionResponse412 | actualizarReglaContabilizacionResponse422 | actualizarReglaContabilizacionResponse428 | actualizarReglaContabilizacionResponse429 | actualizarReglaContabilizacionResponse500) & {
  headers: Headers;
};

export type actualizarReglaContabilizacionResponse = (actualizarReglaContabilizacionResponseSuccess | actualizarReglaContabilizacionResponseError)

export const getActualizarReglaContabilizacionUrl = (reglaId: string,) => {




  return `/contabilidad/reglas-contabilizacion/${reglaId}`
}

/**
 * Reemplaza la cuenta y el estado de una regla; el tipo de operación, la categoría y el código no cambian. No existe GET individual, así que If-Match es la version de la regla (leída del listado) entre comillas, con el mismo formato del ETag; la respuesta devuelve el nuevo ETag. Una regla activa exige una cuenta (PLT-002 si activa es true y cuentaId es nulo, ADR-035); la cuenta debe existir, estar activa y ser de detalle (CON-006). Rol mínimo: contador.
 * @summary Reemplaza una regla de contabilización
 */
export const actualizarReglaContabilizacion = async (reglaId: string,
    actualizacionReglaContabilizacion: ActualizacionReglaContabilizacion, options?: Parameters<typeof clienteHttp>[1]): Promise<actualizarReglaContabilizacionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<actualizarReglaContabilizacionResponse>(getActualizarReglaContabilizacionUrl(reglaId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(actualizacionReglaContabilizacion)
  }
);}





export const getActualizarReglaContabilizacionQueryKey = (reglaId: string,
    actualizacionReglaContabilizacion?: ActualizacionReglaContabilizacion,) => {
    return [
    'PUT', `/contabilidad/reglas-contabilizacion/${reglaId}`, actualizacionReglaContabilizacion
    ] as const;
    }


export const getActualizarReglaContabilizacionQueryOptions = <TData = Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(reglaId: string,
    actualizacionReglaContabilizacion: ActualizacionReglaContabilizacion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActualizarReglaContabilizacionQueryKey(reglaId,actualizacionReglaContabilizacion);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>> = ({ signal }) => actualizarReglaContabilizacion(reglaId,actualizacionReglaContabilizacion, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: reglaId !== null && reglaId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActualizarReglaContabilizacionQueryResult = NonNullable<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>>
export type ActualizarReglaContabilizacionQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useActualizarReglaContabilizacion<TData = Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 reglaId: string,
    actualizacionReglaContabilizacion: ActualizacionReglaContabilizacion, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof actualizarReglaContabilizacion>>,
          TError,
          Awaited<ReturnType<typeof actualizarReglaContabilizacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActualizarReglaContabilizacion<TData = Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 reglaId: string,
    actualizacionReglaContabilizacion: ActualizacionReglaContabilizacion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof actualizarReglaContabilizacion>>,
          TError,
          Awaited<ReturnType<typeof actualizarReglaContabilizacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActualizarReglaContabilizacion<TData = Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 reglaId: string,
    actualizacionReglaContabilizacion: ActualizacionReglaContabilizacion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Reemplaza una regla de contabilización
 */

export function useActualizarReglaContabilizacion<TData = Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 reglaId: string,
    actualizacionReglaContabilizacion: ActualizacionReglaContabilizacion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarReglaContabilizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActualizarReglaContabilizacionQueryOptions(reglaId,actualizacionReglaContabilizacion,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






