/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dato editable del espacio de trabajo: solo el nombre. Nombre comercial, NIT y NRC no se capturan en la versión abierta (ADR-031, ADR-032); son de la edición Enterprise.
 */
export interface ActualizacionEmpresa {
  /**
     * Nuevo nombre del espacio de trabajo.
     * @minLength 1
     * @maxLength 250
     */
  nombre: string;
}
