/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cuenta y estado de una regla (PUT completo); ambos campos son obligatorios.
 */
export interface ActualizacionReglaContabilizacion {
  /**
     * Cuenta de detalle activa de la regla (CON-006); nula solo si activa es false.
     * @nullable
     */
  cuentaId: string | null;
  /** true activa la regla y exige cuentaId (PLT-002 si es nulo); false la desactiva. */
  activa: boolean;
}
