/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cambio del consentimiento de correos; nombre, correo y teléfono vienen de Keycloak y no se editan aquí.
 */
export interface ActualizacionUsuarioActual {
  /** true da el consentimiento; false lo retira. */
  recomendacionesCorreo: boolean;
}
