/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Datos editables de la empresa. Los cuatro campos son obligatorios en el cuerpo y los tres últimos aceptan null para vaciarlos, porque con openApiNullable=false el generador no distingue "ausente" de "nulo". El tipo no es editable.
 */
export interface ActualizacionEmpresa {
  /**
     * Nombre de la empresa.
     * @minLength 1
     * @maxLength 250
     */
  nombre: string;
  /**
     * Nombre comercial; null lo vacía.
     * @maxLength 250
     * @nullable
     */
  nombreComercial: string | null;
  /**
     * NIT de 14 dígitos; null lo vacía (solo válido si la empresa no exige NIT).
     * @nullable
     * @pattern ^[0-9]{14}$
     */
  nit: string | null;
  /**
     * NRC; null lo vacía. [VERIFICAR] formato con la fuente oficial del MH (ADR-029).
     * @maxLength 10
     * @nullable
     */
  nrc: string | null;
}
