/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { NaturalezaCuenta } from './naturalezaCuenta';

/**
 * Campos editables de una cuenta; solo se envían los que cambian y debe venir al menos uno.
 */
export interface ActualizacionCuentaContable {
  /**
     * Nuevo código; no puede cambiarse si la cuenta tiene movimientos (CON-011).
     * @pattern ^[0-9]{1,8}$
     */
  codigo?: string;
  /**
     * Nuevo nombre de la cuenta.
     * @minLength 1
     * @maxLength 200
     */
  nombre?: string;
  /** Nueva naturaleza, para cuentas complementarias. */
  naturaleza?: NaturalezaCuenta;
  /** false desactiva la cuenta (CON-012 si tiene saldo, CON-016 si está en uso); true la reactiva. */
  activa?: boolean;
}
