/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Alcance que otorga una API key; en 1.0 solo el webhook de operaciones de n8n.
 */
export type AlcanceApiKey = typeof AlcanceApiKey[keyof typeof AlcanceApiKey];


export const AlcanceApiKey = {
  'integracion:operaciones': 'integracion:operaciones',
} as const;
