/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { ApiKey } from './apiKey';

/**
 * API key recién creada; es la única respuesta que incluye el secreto.
 */
export type ApiKeyCreada = ApiKey & {
  /** Secreto completo (pk_xxxx.secreto). Se muestra una sola vez y no se puede recuperar; el servidor guarda únicamente su hash Argon2id. */
  secreto: string;
};
