/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { EdicionAplicacion } from './edicionAplicacion';
import type { EstadoAplicacion } from './estadoAplicacion';

/**
 * App del catálogo con su estado para la empresa activa.
 */
export interface AplicacionCatalogo {
  /** Identificador estable de la app; también es el prefijo de sus rutas. */
  codigo: string;
  /** Nombre visible de la app. */
  nombre: string;
  /**
     * Descripción corta de la app.
     * @nullable
     */
  descripcion: string | null;
  edicion: EdicionAplicacion;
  estado: EstadoAplicacion;
  /**
     * Instante UTC de la instalación (FechaHora); nulo si la app no está instalada.
     * @nullable
     */
  instaladaEn: string | null;
}
