/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { DestinoFondos } from './destinoFondos';
import type { Fecha } from './fecha';
import type { MontoEntrada } from './montoEntrada';

/**
 * Datos de un aporte de capital (ADR-041 §5.3); acredita la cuenta de capital.
 */
export interface AporteSolicitud {
  /** Fecha contable del aporte; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Descripción del aporte; forma parte del concepto del asiento.
     * @minLength 1
     * @maxLength 300
     */
  descripcion: string;
  /** Monto aportado. */
  monto: MontoEntrada;
  /** Cuenta de efectivo o banco donde se recibe el aporte. */
  destino: DestinoFondos;
}
