/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { FilaBalanza } from './filaBalanza';
import type { Monto } from './monto';

/**
 * Balanza de Comprobación con una fila por cuenta hasta el nivel pedido. Los totales se calculan solo con las cuentas de detalle, para no contar dos veces los saldos de las cuentas padre (ADR-038 §6).
 */
export interface BalanzaComprobacion {
  desde: Fecha;
  hasta: Fecha;
  /**
     * Nivel del catálogo hasta el que se agrupan las filas.
     * @minimum 1
     * @maximum 5
     */
  nivel: number;
  /** Filas de la balanza ordenadas por código. */
  filas: FilaBalanza[];
  /** Σ Debe de las cuentas de detalle. */
  totalDebe: Monto;
  /** Σ Haber de las cuentas de detalle. */
  totalHaber: Monto;
  /** Σ de los saldos finales del lado deudor de las cuentas de detalle. */
  totalSaldosDeudores: Monto;
  /** Σ de los saldos finales del lado acreedor de las cuentas de detalle. */
  totalSaldosAcreedores: Monto;
  /** true si Σ Debe = Σ Haber y Σ saldos deudores = Σ saldos acreedores (siempre se cumple, por la partida doble). */
  cuadra: boolean;
}
