/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoría de la regla de contabilización (ADR-020, ampliada por ADR-041 §5.3-§5.5): INGRESO un concepto de venta, COBRO una forma de cobro, PAGO una forma de pago, GASTO un destino de compra o gasto, CONTRAPARTIDA la cuenta de la contraparte de un cobro, pago, aporte o préstamo, ACTIVO una categoría de activo fijo y DEPRECIACION su cuenta de depreciación acumulada o de gasto.
 */
export type CategoriaRegla = typeof CategoriaRegla[keyof typeof CategoriaRegla];


export const CategoriaRegla = {
  INGRESO: 'INGRESO',
  COBRO: 'COBRO',
  PAGO: 'PAGO',
  GASTO: 'GASTO',
  CONTRAPARTIDA: 'CONTRAPARTIDA',
  ACTIVO: 'ACTIVO',
  DEPRECIACION: 'DEPRECIACION',
} as const;
