/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoría del activo fijo (spec F4.5 §5.5); resuelve la cuenta de activo por la regla ACTIVO y la de depreciación acumulada por la regla DEPRECIACION. TERRENO no se deprecia.
 */
export type CategoriaActivo = typeof CategoriaActivo[keyof typeof CategoriaActivo];


export const CategoriaActivo = {
  MOBILIARIO_EQUIPO: 'MOBILIARIO_EQUIPO',
  EQUIPO_COMPUTO: 'EQUIPO_COMPUTO',
  VEHICULO: 'VEHICULO',
  EDIFICIO: 'EDIFICIO',
  TERRENO: 'TERRENO',
} as const;
