/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Categoría de la regla; INGRESO es un concepto de venta y COBRO una forma de pago (ADR-020).
 */
export type CategoriaRegla = typeof CategoriaRegla[keyof typeof CategoriaRegla];


export const CategoriaRegla = {
  INGRESO: 'INGRESO',
  COBRO: 'COBRO',
} as const;
