/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tabla de origen de la entrada de bitácora: OPERACION (operacion_externa, aceptada) o RECHAZO (intento_operacion_externa, rechazada).
 */
export type ClaseEntradaBitacora = typeof ClaseEntradaBitacora[keyof typeof ClaseEntradaBitacora];


export const ClaseEntradaBitacora = {
  OPERACION: 'OPERACION',
  RECHAZO: 'RECHAZO',
} as const;
