/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { DestinoFondos } from './destinoFondos';
import type { Fecha } from './fecha';
import type { MontoEntrada } from './montoEntrada';
import type { OrigenCobro } from './origenCobro';

/**
 * Datos de un cobro a un cliente (ADR-041 §5.3). Con origen CLIENTES acredita la cartera de clientes; con TARJETAS acredita la cuenta de tarjetas por el monto bruto y registra la comisión y el anticipo de IVA de la liquidación tal como los ingresa el usuario — Pilot no aplica tasas.
 */
export interface CobroClienteSolicitud {
  /** Fecha contable del cobro; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Descripción del cobro; forma parte del concepto del asiento.
     * @minLength 1
     * @maxLength 300
     */
  descripcion: string;
  origen: OrigenCobro;
  /** Monto bruto cobrado, antes de comisión y anticipo de IVA. */
  monto: MontoEntrada;
  /** Cuenta de efectivo o banco donde se recibe el neto del cobro. */
  destino: DestinoFondos;
  /** Comisión de la liquidación de tarjetas, tal como viene en ella; solo aplica con origen TARJETAS. */
  comision?: MontoEntrada;
  /** Anticipo de IVA de la liquidación de tarjetas, tal como viene en ella; solo aplica con origen TARJETAS. */
  anticipoIva?: MontoEntrada;
}
