/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { DestinoGasto } from './destinoGasto';
import type { DocumentoCompra } from './documentoCompra';
import type { Fecha } from './fecha';
import type { FormaPago } from './formaPago';
import type { ModoPrecio } from './modoPrecio';
import type { MontoEntrada } from './montoEntrada';

/**
 * Datos de una compra o un gasto (ADR-041 §5.3, §5.4). Con documento CREDITO_FISCAL separa la base y el IVA crédito fiscal; con FACTURA el total va al destino sin separar IVA (CLAUDE.md §11.2).
 */
export interface CompraGastoSolicitud {
  /** Fecha contable de la compra o el gasto; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Descripción de la compra o el gasto; forma parte del concepto del asiento.
     * @minLength 1
     * @maxLength 300
     */
  descripcion: string;
  destino: DestinoGasto;
  documento: DocumentoCompra;
  /** Monto del documento, interpretado según modoPrecio si es CREDITO_FISCAL, o total si es FACTURA. */
  monto: MontoEntrada;
  /** Modo de precio para separar el IVA; solo aplica con documento CREDITO_FISCAL. */
  modoPrecio?: ModoPrecio;
  formaPago: FormaPago;
}
