/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { NaturalezaCuenta } from './naturalezaCuenta';
import type { Uuid } from './uuid';

/**
 * Cuenta del catálogo de la empresa; también viaja su versión como ETag.
 */
export interface CuentaContable {
  id: Uuid;
  /** Código de la cuenta; su primer dígito es la clase. */
  codigo: string;
  /** Nombre de la cuenta. */
  nombre: string;
  /**
     * Clase de la cuenta (primer dígito del código) 1 Activo, 2 Pasivo, 3 Capital, 4 Costos y Gastos, 5 Ingresos.
     * @minimum 1
     * @maximum 5
     */
  clase: number;
  /**
     * Nivel por longitud del código, 1 clase, 2 grupo, 3 cuenta, 4 subcuenta, 5 detalle.
     * @minimum 1
     * @maximum 5
     */
  nivel: number;
  /**
     * Cuenta padre (su código es prefijo del de esta cuenta); nulo en las clases.
     * @nullable
     */
  cuentaPadreId: string | null;
  /** Naturaleza de la cuenta; de solo lectura, derivada de la cuenta padre o de la clase en el nivel 1 (ADR-042). Ya no se envía al crear ni al editar una cuenta. */
  naturaleza: NaturalezaCuenta;
  /** true solo en las cuentas de detalle, sin hijas; únicas que aceptan movimientos. */
  aceptaMovimientos: boolean;
  /** Si la cuenta está activa; una cuenta inactiva no acepta movimientos. */
  activa: boolean;
  /** Versión para concurrencia optimista; también viaja como ETag (CLAUDE.md §8.3). */
  version: number;
  /** true si la cuenta viene del catálogo base: su código, nombre, naturaleza y estado no se editan (422 CON-021, ADR-042). El usuario agrega subcuentas propias bajo las cuentas base que no son de detalle, y esas sí las edita. */
  readonly sistema: boolean;
}
