/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { DestinoFondos } from './destinoFondos';
import type { Fecha } from './fecha';
import type { MontoEntrada } from './montoEntrada';
import type { PlazoPrestamo } from './plazoPrestamo';

/**
 * Datos del pago de una cuota de préstamo (ADR-041 §5.3); debita el capital contra el pasivo del plazo, los intereses y, si aplica, la comisión, contra la cuenta de origen.
 */
export interface CuotaPrestamoSolicitud {
  /** Fecha contable de la cuota; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Descripción de la cuota; forma parte del concepto del asiento.
     * @minLength 1
     * @maxLength 300
     */
  descripcion: string;
  /** Plazo del préstamo al que pertenece la cuota, para debitar el pasivo correspondiente. */
  plazo: PlazoPrestamo;
  /** Parte de la cuota que abona al capital del préstamo. */
  capital: MontoEntrada;
  /** Parte de la cuota que corresponde a intereses. */
  intereses: MontoEntrada;
  /** Comisión de la cuota, si la hay; "0" si no aplica. */
  comision?: MontoEntrada;
  /** Cuenta de efectivo o banco de donde sale el pago de la cuota. */
  origen: DestinoFondos;
}
