/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Mes a depreciar (ADR-041 §5.5); sin fecha ni descripción, porque genera un asiento por cada categoría con activos vigentes. Responde 422 CON-023 si alguna vida útil de las categorías con activos no está confirmada por el contador.
 */
export interface DepreciacionSolicitud {
  /**
     * Año a depreciar; no puede ser posterior al mes y año actuales en hora de El Salvador.
     * @minimum 2000
     * @maximum 9999
     */
  anio: number;
  /**
     * Mes a depreciar (1 a 12); una sola depreciación por activo y mes (índice único).
     * @minimum 1
     * @maximum 12
     */
  mes: number;
}
