/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { MontoConSigno } from './montoConSigno';

/**
 * Desglose de un IVA (débito o crédito fiscal) por el origen del asiento.
 */
export interface DesgloseIva {
  /** Movimiento de asientos de origen MANUAL. */
  manual: MontoConSigno;
  /** Movimiento de asientos de origen N8N. */
  n8n: MontoConSigno;
  /** Movimiento de asientos de origen REVERSION. */
  reversion: MontoConSigno;
  /** Suma de manual, n8n y reversion. */
  total: MontoConSigno;
}
