/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Destino de una compra o gasto (spec F4.5 §5.4); resuelve la cuenta por la regla GASTO del tipo COMPRA_GASTO. OTRO_GASTO no tiene cuenta por defecto y queda inactiva hasta configurarla (422 CON-020).
 */
export type DestinoGasto = typeof DestinoGasto[keyof typeof DestinoGasto];


export const DestinoGasto = {
  MERCADERIA: 'MERCADERIA',
  ALQUILER: 'ALQUILER',
  SERVICIOS_BASICOS: 'SERVICIOS_BASICOS',
  PAPELERIA: 'PAPELERIA',
  SUELDOS_ADMINISTRACION: 'SUELDOS_ADMINISTRACION',
  SUELDOS_VENTAS: 'SUELDOS_VENTAS',
  HONORARIOS: 'HONORARIOS',
  PUBLICIDAD: 'PUBLICIDAD',
  COMISIONES_BANCARIAS: 'COMISIONES_BANCARIAS',
  OTRO_GASTO: 'OTRO_GASTO',
} as const;
