/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cuenta de efectivo o de banco de origen o de destino de un movimiento de fondos (spec F4.5 §5.3); resuelve la cuenta por la regla COBRO o PAGO según la operación.
 */
export type DestinoFondos = typeof DestinoFondos[keyof typeof DestinoFondos];


export const DestinoFondos = {
  EFECTIVO: 'EFECTIVO',
  BANCO: 'BANCO',
} as const;
