/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { DiferenciaMayorizacion } from './diferenciaMayorizacion';

/**
 * Resultado de verificar que saldo_cuenta_mensual sea igual a la suma de asiento_linea (ADR-018).
 */
export interface DiagnosticoMayorizacion {
  /** true si no se encontró ninguna diferencia. */
  consistente: boolean;
  /** Cantidad de combinaciones de cuenta, año y mes revisadas. */
  cantidadCuentasRevisadas: number;
  /** Diferencias encontradas; vacío si consistente es true. */
  diferencias: DiferenciaMayorizacion[];
}
