/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Monto } from './monto';
import type { ResumenCuenta } from './resumenCuenta';

/**
 * Diferencia entre saldo_cuenta_mensual y la suma de las líneas de una cuenta, año y mes.
 */
export interface DiferenciaMayorizacion {
  cuenta: ResumenCuenta;
  /** Año del saldo mensual con diferencia. */
  anio: number;
  /**
     * Mes del saldo mensual con diferencia.
     * @minimum 1
     * @maximum 12
     */
  mes: number;
  /** total_debe almacenado en saldo_cuenta_mensual. */
  saldoDebe: Monto;
  /** total_haber almacenado en saldo_cuenta_mensual. */
  saldoHaber: Monto;
  /** Σ debe de asiento_linea para la cuenta, año y mes. */
  lineasDebe: Monto;
  /** Σ haber de asiento_linea para la cuenta, año y mes. */
  lineasHaber: Monto;
}
