/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Edición a la que pertenece la app; solo las COMUNITARIA se pueden instalar en 1.0 (ADR-030).
 */
export type EdicionAplicacion = typeof EdicionAplicacion[keyof typeof EdicionAplicacion];


export const EdicionAplicacion = {
  COMUNITARIA: 'COMUNITARIA',
  ENTERPRISE: 'ENTERPRISE',
} as const;
