/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { EstadoEmpresa } from './estadoEmpresa';
import type { TipoEmpresa } from './tipoEmpresa';
import type { Uuid } from './uuid';

/**
 * Empresa activa de la sesión.
 */
export interface Empresa {
  id: Uuid;
  tipo: TipoEmpresa;
  /** Nombre de la empresa. */
  nombre: string;
  /**
     * Nombre comercial; nulo si no se ha registrado.
     * @nullable
     */
  nombreComercial: string | null;
  /**
     * NIT de 14 dígitos; opcional en la empresa PERSONAL, nulo si no se ha registrado.
     * @nullable
     * @pattern ^[0-9]{14}$
     */
  nit: string | null;
  /**
     * Número de Registro de Contribuyente; nulo si no es contribuyente. [VERIFICAR] formato del NRC con la fuente oficial del MH (ADR-029); por eso no tiene patrón.
     * @maxLength 10
     * @nullable
     */
  nrc: string | null;
  estado: EstadoEmpresa;
  /** Versión para concurrencia optimista; también viaja como ETag (CLAUDE.md §8.3). */
  version: number;
}
