/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { ClaseEntradaBitacora } from './claseEntradaBitacora';
import type { Fecha } from './fecha';
import type { FechaHora } from './fechaHora';
import type { ResultadoBitacora } from './resultadoBitacora';
import type { TipoOperacionContable } from './tipoOperacionContable';
import type { Uuid } from './uuid';

/**
 * Entrada de la bitácora unificada de operaciones y rechazos, sin datos personales. Los campos que no aplican a la clase de la entrada van nulos.
 */
export interface EntradaBitacora {
  id: Uuid;
  clase: ClaseEntradaBitacora;
  resultado: ResultadoBitacora;
  /** Tipo de la operación; nulo si un rechazo no llegó a identificarlo. */
  tipoOperacion: TipoOperacionContable | null;
  /**
     * Sistema de origen de la operación; nulo si un rechazo no llegó a identificarlo.
     * @nullable
     */
  sistemaOrigen: string | null;
  /**
     * Identificador externo de la operación; nulo en un rechazo sin cuerpo legible.
     * @nullable
     */
  idExterno: string | null;
  /** Fecha contable de la operación (clase OPERACION); nula en un RECHAZO. */
  fechaOperacion: Fecha | null;
  /**
     * Total normalizado de la operación como cadena decimal (ADR-013); nulo en un RECHAZO. El servidor siempre responde con exactamente 2 decimales.
     * @nullable
     * @pattern ^\d{1,17}(\.\d{1,2})?$
     */
  total: string | null;
  /**
     * Código INT- o CON- del rechazo (clase RECHAZO); nulo en una OPERACION.
     * @nullable
     */
  codigoError: string | null;
  /**
     * Asiento generado (clase OPERACION); nulo en un RECHAZO.
     * @nullable
     */
  asientoId: string | null;
  /** Instante UTC en que Pilot recibió la petición. */
  recibidoEn: FechaHora;
}
