/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemDetails } from './problemDetails';

/**
 * 500 — Error interno; no expone trazas ni mensajes internos. Reintentar es seguro con idempotencia.
 */
export type ErrorInternoResponse = ProblemDetails;
