/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Estado del activo fijo; pasa a REVERTIDO cuando se revierte el asiento de su compra (ADR-041 §5.5). No hay baja ni venta de activos en 1.0.
 */
export type EstadoActivoFijo = typeof EstadoActivoFijo[keyof typeof EstadoActivoFijo];


export const EstadoActivoFijo = {
  EN_USO: 'EN_USO',
  REVERTIDO: 'REVERTIDO',
} as const;
