/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Estado de la app para la empresa activa (ADR-030).
 */
export type EstadoAplicacion = typeof EstadoAplicacion[keyof typeof EstadoAplicacion];


export const EstadoAplicacion = {
  INSTALADA: 'INSTALADA',
  DISPONIBLE: 'DISPONIBLE',
  BLOQUEADA_ENTERPRISE: 'BLOQUEADA_ENTERPRISE',
} as const;
