/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Estado de una operación externa; pasa a REVERTIDO cuando se revierte el asiento que generó (CLAUDE.md §12.8).
 */
export type EstadoOperacionExterna = typeof EstadoOperacionExterna[keyof typeof EstadoOperacionExterna];


export const EstadoOperacionExterna = {
  CONTABILIZADO: 'CONTABILIZADO',
  REVERTIDO: 'REVERTIDO',
} as const;
