/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { MontoConSigno } from './montoConSigno';
import type { RubroEstado } from './rubroEstado';

/**
 * Estado de Resultados de gestión en un rango de fechas, con el impuesto sobre la renta aparte (ADR-037).
 */
export interface EstadoResultados {
  desde: Fecha;
  hasta: Fecha;
  /**
     * Nivel del catálogo hasta el que se agrupan las filas.
     * @minimum 1
     * @maximum 5
     */
  nivel: number;
  /** Rubro de la clase 5. */
  ingresos: RubroEstado;
  /** Rubro de la clase 4, sin el grupo 44 (impuesto sobre la renta). */
  costosGastos: RubroEstado;
  /** Ingresos − Costos y gastos. */
  utilidadAntesImpuesto: MontoConSigno;
  /** Rubro del grupo 44 (impuesto sobre la renta), aparte de costosGastos (ADR-037). */
  impuestoSobreRenta: RubroEstado;
  /** Utilidad antes de impuesto − Impuesto sobre la renta. */
  utilidadEjercicio: MontoConSigno;
  /** "Estado de gestión generado por Pilot; no constituye un juego completo de estados financieros conforme a NIIF para PYMES" (ADR-037 §3). */
  leyenda: string;
}
