/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { AnioReporteParameter } from './anioReporteParameter';
import type { FormatoParameter } from './formatoParameter';
import type { MesReporteParameter } from './mesReporteParameter';

export type ExportarResumenIvaParams = {
/**
 * Formato del archivo exportado (ADR-038).
 */
formato: FormatoParameter;
/**
 * Año del período del reporte.
 * @minimum 2000
 * @maximum 9999
 */
anio: AnioReporteParameter;
/**
 * Mes del período del reporte (1 a 12).
 * @minimum 1
 * @maximum 12
 */
mes: MesReporteParameter;
};
