/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Monto } from './monto';
import type { ResumenCuenta } from './resumenCuenta';
import type { Saldo } from './saldo';

/**
 * Fila de la Balanza de Comprobación para una cuenta hasta el nivel pedido.
 */
export interface FilaBalanza {
  cuenta: ResumenCuenta;
  /**
     * Nivel de la cuenta por longitud de código (CLAUDE.md §10.2).
     * @minimum 1
     * @maximum 5
     */
  nivel: number;
  /** true si es una cuenta de detalle; los totales de la balanza salen solo de estas filas (ADR-038 §6). */
  esDetalle: boolean;
  /** Saldo acumulado antes de desde. */
  saldoInicial: Saldo;
  /** Suma del Debe en el rango. */
  debe: Monto;
  /** Suma del Haber en el rango. */
  haber: Monto;
  /** Saldo acumulado al final de hasta. */
  saldoFinal: Saldo;
}
