/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Forma en que el cliente pagó una venta (spec F4.5 §5.3); resuelve la cuenta de contrapartida por la regla COBRO del tipo VENTA.
 */
export type FormaCobro = typeof FormaCobro[keyof typeof FormaCobro];


export const FormaCobro = {
  EFECTIVO: 'EFECTIVO',
  BANCO: 'BANCO',
  TARJETA: 'TARJETA',
  CREDITO: 'CREDITO',
} as const;
