/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * ETag de la versión leída del recurso; si no coincide con la actual se responde 412 PLT-016 (CLAUDE.md §8.3).
 */
export type IfMatchParameter = string;
