/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Lado del saldo de una cuenta — DEUDOR, ACREEDOR o CERO cuando Debe y Haber son iguales (CLAUDE.md §10.3).
 */
export type LadoSaldo = typeof LadoSaldo[keyof typeof LadoSaldo];


export const LadoSaldo = {
  DEUDOR: 'DEUDOR',
  ACREEDOR: 'ACREEDOR',
  CERO: 'CERO',
} as const;
