/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { Monto } from './monto';
import type { MovimientoMayor } from './movimientoMayor';
import type { NaturalezaCuenta } from './naturalezaCuenta';
import type { ResumenCuenta } from './resumenCuenta';
import type { Saldo } from './saldo';

/**
 * Libro Mayor / auxiliar de una cuenta (o de sus cuentas de detalle si es una cuenta padre) en un rango de fechas.
 */
export interface LibroMayor {
  /** Cuenta consultada; puede ser una cuenta padre (ADR-038 §5). */
  cuenta: ResumenCuenta;
  naturaleza: NaturalezaCuenta;
  desde: Fecha;
  hasta: Fecha;
  /** Saldo acumulado antes de desde. */
  saldoInicial: Saldo;
  /** Movimientos en el rango, ordenados por fecha, con saldo acumulado línea a línea. */
  movimientos: MovimientoMayor[];
  /** Suma del Debe de los movimientos del rango. */
  totalDebe: Monto;
  /** Suma del Haber de los movimientos del rango. */
  totalHaber: Monto;
  /** Saldo acumulado al final de hasta. */
  saldoFinal: Saldo;
}
