/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Monto } from './monto';
import type { OrigenLinea } from './origenLinea';
import type { ResumenCuenta } from './resumenCuenta';
import type { Uuid } from './uuid';

/**
 * Línea de un asiento guardado, ya expandida.
 */
export interface LineaAsiento {
  id: Uuid;
  /**
     * Posición de la línea dentro del asiento, desde 1.
     * @minimum 1
     */
  numeroLinea: number;
  cuenta: ResumenCuenta;
  /**
     * Descripción de la línea; nula si no tiene.
     * @nullable
     */
  descripcion: string | null;
  debe: Monto;
  haber: Monto;
  origenLinea: OrigenLinea;
  /**
     * En una línea de IVA calculado, la línea que la originó; nulo en las demás.
     * @nullable
     */
  lineaBaseId: string | null;
}
