/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { BusquedaCuentaParameter } from './busquedaCuentaParameter';
import type { SoloActivasParameter } from './soloActivasParameter';
import type { SoloDetalleParameter } from './soloDetalleParameter';

export type ListarCuentasContablesParams = {
/**
 * Texto a buscar en el código o el nombre de la cuenta, sin distinguir mayúsculas.
 * @maxLength 100
 */
busqueda?: BusquedaCuentaParameter;
/**
 * true devuelve solo las cuentas de detalle (las que aceptan movimientos).
 */
soloDetalle?: SoloDetalleParameter;
/**
 * true omite las cuentas inactivas.
 */
soloActivas?: SoloActivasParameter;
};
