/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { AnioFiltroParameter } from './anioFiltroParameter';
import type { CuentaIdFiltroParameter } from './cuentaIdFiltroParameter';
import type { CursorParameter } from './cursorParameter';
import type { DesdeParameter } from './desdeParameter';
import type { EstadoAsientoFiltroParameter } from './estadoAsientoFiltroParameter';
import type { HastaParameter } from './hastaParameter';
import type { LimiteParameter } from './limiteParameter';
import type { NumeroAsientoFiltroParameter } from './numeroAsientoFiltroParameter';
import type { OrigenAsientoFiltroParameter } from './origenAsientoFiltroParameter';

export type ListarAsientosParams = {
/**
 * Cantidad máxima de elementos por página.
 * @minimum 1
 * @maximum 200
 */
limite?: LimiteParameter;
/**
 * Cursor opaco devuelto como siguienteCursor en la página anterior.
 */
cursor?: CursorParameter;
/**
 * Fecha calendario ISO-8601 (AAAA-MM-DD); las fechas contables son de hora de El Salvador.
 */
desde?: DesdeParameter;
/**
 * Fecha calendario ISO-8601 (AAAA-MM-DD); las fechas contables son de hora de El Salvador.
 */
hasta?: HastaParameter;
/**
 * Año de la fecha contable de los asientos.
 * @minimum 2000
 * @maximum 9999
 */
anio?: AnioFiltroParameter;
/**
 * Número correlativo del asiento (se combina con anio para ubicar uno solo).
 * @minimum 1
 */
numero?: NumeroAsientoFiltroParameter;
/**
 * Cómo nació el asiento — registro manual, operación recibida por n8n o reversión de otro asiento.
 */
origen?: OrigenAsientoFiltroParameter;
/**
 * Estado del asiento; REVERTIDO es el único cambio permitido tras guardarlo (ADR-019).
 */
estado?: EstadoAsientoFiltroParameter;
/**
 * Identificador UUID (versión 7 generado por la aplicación, ADR-010).
 */
cuentaId?: CuentaIdFiltroParameter;
};
