/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { TipoOperacionFiltroParameter } from './tipoOperacionFiltroParameter';

export type ListarReglasContabilizacionParams = {
/**
 * Tipo de operación que contabiliza el motor único ContabilizarOperacion (ADR-041 §5.2): los diez tipos guiados más CIERRE_INGRESOS_DIARIO, que llega por el webhook de n8n y usa el mismo motor. Se usa en las reglas de contabilización, en el registro y en la consulta de operaciones guiadas.
 */
tipoOperacion?: TipoOperacionFiltroParameter;
};
