/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { EstadoMembresia } from './estadoMembresia';
import type { FechaHora } from './fechaHora';
import type { Rol } from './rol';
import type { Uuid } from './uuid';

/**
 * Usuario que pertenece a la empresa activa, con su rol y estado.
 */
export interface MiembroEmpresa {
  usuarioId: Uuid;
  /** Nombre completo del usuario. */
  nombre: string;
  /** Correo del usuario (dato personal; se enmascara en logs). */
  correo: string;
  rol: Rol;
  estado: EstadoMembresia;
  desde: FechaHora;
}
