/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cómo se interpreta un monto: CON_IVA (el monto incluye IVA) o SIN_IVA (el IVA se suma). Solo cambia la interpretación, no las tasas (ADR-015).
 */
export type ModoPrecio = typeof ModoPrecio[keyof typeof ModoPrecio];


export const ModoPrecio = {
  CON_IVA: 'CON_IVA',
  SIN_IVA: 'SIN_IVA',
} as const;
