/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Monto de entrada de una línea de asiento como cadena decimal, con signo opcional y cualquier cantidad de decimales. Solo se usa al enviar líneas: es deliberadamente más permisivo que Monto para que la validación de forma no rechace un negativo ni más de 2 decimales, y sea la regla de negocio la que responda CON-003 (ADR-036). Nunca número JSON (ADR-013).
 * @pattern ^-?\d{1,17}(\.\d+)?$
 */
export type MontoEntrada = string;
