/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { Monto } from './monto';
import type { ResumenCuenta } from './resumenCuenta';
import type { Saldo } from './saldo';
import type { Uuid } from './uuid';

/**
 * Movimiento del Libro Mayor con el saldo acumulado tras aplicarlo.
 */
export interface MovimientoMayor {
  fecha: Fecha;
  /** Asiento al que pertenece la línea. */
  asientoId: Uuid;
  /** Año del asiento; junto con numero forma su correlativo. */
  anio: number;
  /** Número correlativo del asiento. */
  numero: number;
  /** Concepto o glosa del asiento. */
  concepto: string;
  /**
     * Descripción de la línea; nula si no tiene.
     * @nullable
     */
  descripcion: string | null;
  /** Cuenta de detalle de la línea; en el Mayor de una cuenta padre, cada movimiento identifica su propia cuenta de detalle (ADR-038 §5). */
  cuenta: ResumenCuenta;
  debe: Monto;
  haber: Monto;
  /** Saldo acumulado de la cuenta consultada inmediatamente después de esta línea. */
  saldo: Saldo;
}
