/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Naturaleza de la cuenta; deudora aumenta con el Debe (clases 1 y 4), acreedora con el Haber (2, 3 y 5).
 */
export type NaturalezaCuenta = typeof NaturalezaCuenta[keyof typeof NaturalezaCuenta];


export const NaturalezaCuenta = {
  DEUDORA: 'DEUDORA',
  ACREEDORA: 'ACREEDORA',
} as const;
