/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { AlcanceApiKey } from './alcanceApiKey';

/**
 * Datos para crear una API key.
 */
export interface NuevaApiKey {
  /**
     * Nombre descriptivo de la clave.
     * @minLength 1
     * @maxLength 100
     */
  nombre: string;
  /**
     * Alcances que tendrá la clave. Sin repetidos: el backend rechaza duplicados con 422 PLT-002.
     * @minItems 1
     */
  alcances: AlcanceApiKey[];
  /**
     * Instante UTC de expiración (FechaHora); null para una clave que no vence.
     * @nullable
     */
  expiraEn: string | null;
}
