/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { NaturalezaCuenta } from './naturalezaCuenta';

/**
 * Datos para crear una cuenta. La cuenta padre no se envía porque se deduce del código (ADR-035). El patrón del código no exige la clase para que la regla de negocio responda CON-010 y CON-015.
 */
export interface NuevaCuentaContable {
  /**
     * Código de 1 a 8 dígitos; su primer dígito debe ser una clase de 1 a 5 (CON-010).
     * @pattern ^[0-9]{1,8}$
     */
  codigo: string;
  /**
     * Nombre de la cuenta.
     * @minLength 1
     * @maxLength 200
     */
  nombre: string;
  /** Naturaleza de la cuenta; si se omite se usa la de su clase. */
  naturaleza?: NaturalezaCuenta;
}
