/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';

/**
 * Datos opcionales de una reversión.
 */
export interface NuevaReversion {
  /** Fecha contable de la reversión; por defecto hoy en hora de El Salvador. No puede ser futura (CON-007) ni anterior a la del asiento original (CON-018). */
  fecha?: Fecha;
}
