/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { ModoPrecio } from './modoPrecio';
import type { NuevaLineaAsiento } from './nuevaLineaAsiento';

/**
 * Datos de un asiento manual. No lleva mínimo de líneas en la forma para que el negocio responda CON-001, ni totales: los calcula el backend.
 */
export interface NuevoAsiento {
  /** Fecha contable en hora de El Salvador; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Concepto o glosa del asiento.
     * @minLength 1
     * @maxLength 500
     */
  concepto: string;
  /** Modo de precio para separar el IVA; si falta se usa el de la configuración contable (ADR-015). */
  modoPrecio?: ModoPrecio;
  /**
     * Líneas del asiento, máximo 200; el mínimo de dos (CON-001) lo valida el negocio.
     * @maxItems 200
     */
  lineas: NuevaLineaAsiento[];
}
