/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { AnioTableroParameter } from './anioTableroParameter';
import type { MesTableroParameter } from './mesTableroParameter';

export type ObtenerTableroParams = {
/**
 * Año del tablero.
 * @minimum 2000
 * @maximum 9999
 */
anio: AnioTableroParameter;
/**
 * Mes del tablero (1 a 12).
 * @minimum 1
 * @maximum 12
 */
mes: MesTableroParameter;
};
