/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { CuentaIdMayorParameter } from './cuentaIdMayorParameter';
import type { DesdeReporteParameter } from './desdeReporteParameter';
import type { HastaReporteParameter } from './hastaReporteParameter';

export type ObtenerLibroMayorParams = {
/**
 * Identificador UUID (versión 7 generado por la aplicación, ADR-010).
 */
cuentaId: CuentaIdMayorParameter;
/**
 * Fecha calendario ISO-8601 (AAAA-MM-DD); las fechas contables son de hora de El Salvador.
 */
desde: DesdeReporteParameter;
/**
 * Fecha calendario ISO-8601 (AAAA-MM-DD); las fechas contables son de hora de El Salvador.
 */
hasta: HastaReporteParameter;
};
