/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { FechaCorteParameter } from './fechaCorteParameter';
import type { IncluirCerosParameter } from './incluirCerosParameter';
import type { NivelReporteParameter } from './nivelReporteParameter';

export type ObtenerEstadoSituacionFinancieraParams = {
/**
 * Fecha calendario ISO-8601 (AAAA-MM-DD); las fechas contables son de hora de El Salvador.
 */
fechaCorte: FechaCorteParameter;
/**
 * Nivel del catálogo hasta el que se agrupan las filas del reporte (1 clase … 5 detalle, CLAUDE.md §10.2).
 * @minimum 1
 * @maximum 5
 */
nivel?: NivelReporteParameter;
/**
 * true incluye también las filas con monto en cero.
 */
incluirCeros?: IncluirCerosParameter;
};
