/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cuerpo de una operación de negocio enviada por n8n. Es intencionalmente un objeto libre y sin properties en este contrato (el generador lo traduce a un Map<String, Object> en vez de una clase de modelo, ADR-039 §3): sus campos, siempre incluidos tipoOperacion (p. ej. CIERRE_INGRESOS_DIARIO) y version (entero, p. ej. 1), eligen el esquema JSON versionado api-spec/esquemas/operaciones/<tipo>/v<n>.json (en 1.0 solo cierre-ingresos-diario/v1.json), contra el que se valida el cuerpo ANTES de interpretarlo (regla 1.1.14 de CLAUDE.md). Un tipoOperacion o version no soportados responden 422 INT-002; un cuerpo que no cumple su esquema JSON, 400 INT-001 con la lista errores. Ver el ejemplo de esta petición en CLAUDE.md §12.3.
 */
export interface OperacionN8n { [key: string]: unknown }
