/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Entrada de negocio ya validada con la que se generó la operación (p. ej. los campos de VentaSolicitud), de solo lectura. Objeto libre y sin properties en este contrato para que el generador lo traduzca a Map<String, Object> en vez de una clase de modelo (mismo patrón de OperacionN8n, ADR-039 §3); sus campos exactos dependen de tipo.
 */
export type OperacionDatos = { [key: string]: unknown };
