/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { EstadoOperacion } from './estadoOperacion';
import type { Fecha } from './fecha';
import type { FechaHora } from './fechaHora';
import type { Monto } from './monto';
import type { OperacionDatos } from './operacionDatos';
import type { ReferenciaAsiento } from './referenciaAsiento';
import type { ResumenOperacionGuiada } from './resumenOperacionGuiada';
import type { TipoOperacion } from './tipoOperacion';
import type { Uuid } from './uuid';

/**
 * Operación guiada registrada, para el listado y el detalle (ADR-041 §5.6).
 */
export interface Operacion {
  id: Uuid;
  tipo: TipoOperacion;
  fecha: Fecha;
  /**
     * Descripción capturada por el usuario; nula en una depreciación (DepreciacionSolicitud no la tiene).
     * @nullable
     */
  descripcion: string | null;
  total: Monto;
  estado: EstadoOperacion;
  asiento: ReferenciaAsiento;
  /** Entrada de negocio ya validada con la que se generó la operación (p. ej. los campos de VentaSolicitud), de solo lectura. Objeto libre y sin properties en este contrato para que el generador lo traduzca a Map<String, Object> en vez de una clase de modelo (mismo patrón de OperacionN8n, ADR-039 §3); sus campos exactos dependen de tipo. */
  readonly datos: OperacionDatos;
  resumen: ResumenOperacionGuiada;
  creadoEn: FechaHora;
  /** Identificador de quien registró la operación (app.usuario_id). */
  creadoPor: string;
}
