/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cómo nació el asiento — registro manual, operación recibida por n8n o reversión de otro asiento.
 */
export type OrigenAsiento = typeof OrigenAsiento[keyof typeof OrigenAsiento];


export const OrigenAsiento = {
  MANUAL: 'MANUAL',
  N8N: 'N8N',
  REVERSION: 'REVERSION',
} as const;
