/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Origen de la línea — capturada por el usuario, IVA calculado por el backend al expandir una línea con "lleva IVA" (CLAUDE.md §11.2) o generada por una operación externa.
 */
export type OrigenLinea = typeof OrigenLinea[keyof typeof OrigenLinea];


export const OrigenLinea = {
  USUARIO: 'USUARIO',
  IVA_CALCULADO: 'IVA_CALCULADO',
  OPERACION: 'OPERACION',
} as const;
