/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { DestinoFondos } from './destinoFondos';
import type { Fecha } from './fecha';
import type { MontoEntrada } from './montoEntrada';

/**
 * Datos de un pago a proveedor (ADR-041 §5.3); debita la cuenta de proveedores.
 */
export interface PagoProveedorSolicitud {
  /** Fecha contable del pago; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Descripción del pago; forma parte del concepto del asiento.
     * @minLength 1
     * @maxLength 300
     */
  descripcion: string;
  /** Monto pagado al proveedor. */
  monto: MontoEntrada;
  /** Cuenta de efectivo o banco de donde sale el pago. */
  origen: DestinoFondos;
}
