/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Plazo del préstamo recibido o de la cuota que se paga — CORTO (pasivo circulante) o LARGO (pasivo no circulante); resuelve la cuenta de la contraparte (spec F4.5 §5.3).
 */
export type PlazoPrestamo = typeof PlazoPrestamo[keyof typeof PlazoPrestamo];


export const PlazoPrestamo = {
  CORTO: 'CORTO',
  LARGO: 'LARGO',
} as const;
