/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { Uuid } from './uuid';

/**
 * Referencia corta al asiento generado por una operación externa.
 */
export interface ReferenciaAsiento {
  id: Uuid;
  /** Año de la fecha contable; junto con numero forma el correlativo (N.º numero/anio). */
  anio: number;
  /** Número correlativo del asiento dentro de la empresa y el año. */
  numero: number;
  fecha: Fecha;
}
