/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { CategoriaRegla } from './categoriaRegla';
import type { ResumenCuenta } from './resumenCuenta';
import type { TipoOperacion } from './tipoOperacion';
import type { Uuid } from './uuid';

/**
 * Regla que asigna una cuenta a un código de una operación (ADR-020, ADR-041); su versión es el valor de If-Match.
 */
export interface ReglaContabilizacion {
  id: Uuid;
  tipoOperacion: TipoOperacion;
  categoria: CategoriaRegla;
  /** Código del concepto, forma de cobro o pago, destino o categoría, p. ej. VENTAS_GRAVADAS o EFECTIVO. */
  codigo: string;
  /** Cuenta de detalle que usa la regla; nula solo si la regla está inactiva (ADR-035). */
  cuenta: ResumenCuenta | null;
  /** Si la regla está activa; una regla activa siempre tiene cuenta. */
  activa: boolean;
  /** Versión para concurrencia optimista; se envía entre comillas como If-Match (CLAUDE.md §8.3). */
  version: number;
  /**
     * Prefijo de código que debe tener la cuenta de esta regla (p. ej. "1101"); de solo lectura. Asignarle una cuenta fuera de este grupo responde 422 CON-022 (ADR-042).
     * @nullable
     */
  readonly prefijoPermitido: string | null;
}
