/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Resultado de la entrada de bitácora, para filtrar el listado.
 */
export type ResultadoBitacora = typeof ResultadoBitacora[keyof typeof ResultadoBitacora];


export const ResultadoBitacora = {
  CONTABILIZADO: 'CONTABILIZADO',
  REVERTIDO: 'REVERTIDO',
  RECHAZADO: 'RECHAZADO',
} as const;
