/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Rol del usuario dentro de la empresa (CLAUDE.md §14.2). El rol técnico integracion no aplica a usuarios.
 */
export type Rol = typeof Rol[keyof typeof Rol];


export const Rol = {
  admin_empresa: 'admin_empresa',
  contador: 'contador',
  auditor: 'auditor',
} as const;
