/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { FilaEstado } from './filaEstado';
import type { MontoConSigno } from './montoConSigno';

/**
 * Rubro de un estado financiero (una clase de cuenta) con sus filas y su total.
 */
export interface RubroEstado {
  /**
     * Clase de cuenta del rubro (CLAUDE.md §10.2).
     * @minimum 1
     * @maximum 5
     */
  clase: number;
  /** Nombre del rubro, p. ej. "Activo" o "Ingresos". */
  nombre: string;
  /** Filas del rubro hasta el nivel pedido, con incluirCeros aplicado. */
  filas: FilaEstado[];
  /** Suma de las cuentas de detalle del rubro. */
  total: MontoConSigno;
}
