/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { LadoSaldo } from './ladoSaldo';
import type { Monto } from './monto';

/**
 * Saldo de una cuenta presentado como valor absoluto y lado (CLAUDE.md §10.3).
 */
export interface Saldo {
  /** Valor absoluto del saldo (Debe − Haber en valor absoluto). */
  monto: Monto;
  lado: LadoSaldo;
  /** true si el saldo queda del lado contrario a la naturaleza de la cuenta (alerta de CLAUDE.md §10.3); false en un saldo CERO. */
  contrarioNaturaleza: boolean;
}
