/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { PendienteSeveridad } from './pendienteSeveridad';
import type { PendienteTipo } from './pendienteTipo';

/**
 * Pendiente accionable mostrado en el tablero de inicio.
 */
export interface TableroPendiente {
  tipo: PendienteTipo;
  severidad: PendienteSeveridad;
  /** Explicación del pendiente en español, sin citar documentos internos. */
  detalle: string;
  /**
     * Cuántos elementos agrupa el pendiente (p. ej. cuántas reglas sin cuenta).
     * @minimum 1
     */
  cantidad: number;
}
