/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Monto } from './monto';

/**
 * Punto de la serie de 6 meses de ingresos y gastos del tablero.
 */
export interface TableroSerieItem {
  /** Año del punto de la serie. */
  anio: number;
  /**
     * Mes del punto de la serie (1 a 12).
     * @minimum 1
     * @maximum 12
     */
  mes: number;
  ingresos: Monto;
  gastos: Monto;
}
