/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Monto } from './monto';
import type { MontoConSigno } from './montoConSigno';

/**
 * Resultado de un mes, para el mes actual y el anterior del tablero.
 */
export interface TableroPeriodo {
  ingresos: Monto;
  costosGastos: Monto;
  /** ingresos − costosGastos; puede ser negativa. */
  utilidad: MontoConSigno;
}
