/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Monto } from './monto';
import type { MontoConSigno } from './montoConSigno';
import type { TableroPendiente } from './tableroPendiente';
import type { TableroPeriodo } from './tableroPeriodo';
import type { TableroSaldoCuenta } from './tableroSaldoCuenta';
import type { TableroSerieItem } from './tableroSerieItem';

/**
 * Indicadores y pendientes del tablero de inicio (ADR-041 §5.7).
 */
export interface Tablero {
  /** Saldo de cada cuenta de detalle del grupo 1101 (caja y bancos). */
  efectivo: TableroSaldoCuenta[];
  /** Saldo de la cuenta 1102 (cuentas por cobrar). */
  porCobrar: Monto;
  /** Saldo de la cuenta 2101 (cuentas por pagar). */
  porPagar: Monto;
  /** Resultado del mes consultado. */
  mes: TableroPeriodo;
  /** Resultado del mes inmediato anterior, para comparar. */
  mesAnterior: TableroPeriodo;
  /** IVA débito menos IVA crédito del mes; positivo es lo estimado a pagar. */
  ivaEstimado: MontoConSigno;
  /**
     * Serie de los últimos 6 meses (incluido el consultado) de ingresos y gastos, en orden cronológico.
     * @minItems 6
     * @maxItems 6
     */
  serie: TableroSerieItem[];
  /** Pendientes accionables de contabilidad, sin datos personales. */
  pendientes: TableroPendiente[];
}
