/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo de operación que contabiliza el motor único ContabilizarOperacion (ADR-041 §5.2): los diez tipos guiados más CIERRE_INGRESOS_DIARIO, que llega por el webhook de n8n y usa el mismo motor. Se usa en las reglas de contabilización, en el registro y en la consulta de operaciones guiadas.
 */
export type TipoOperacion = typeof TipoOperacion[keyof typeof TipoOperacion];


export const TipoOperacion = {
  VENTA: 'VENTA',
  COMPRA_GASTO: 'COMPRA_GASTO',
  COBRO_CLIENTE: 'COBRO_CLIENTE',
  PAGO_PROVEEDOR: 'PAGO_PROVEEDOR',
  APORTE_CAPITAL: 'APORTE_CAPITAL',
  PRESTAMO_RECIBIDO: 'PRESTAMO_RECIBIDO',
  PAGO_CUOTA: 'PAGO_CUOTA',
  TRASLADO_FONDOS: 'TRASLADO_FONDOS',
  COMPRA_ACTIVO_FIJO: 'COMPRA_ACTIVO_FIJO',
  DEPRECIACION_MENSUAL: 'DEPRECIACION_MENSUAL',
  CIERRE_INGRESOS_DIARIO: 'CIERRE_INGRESOS_DIARIO',
} as const;
