/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { Fecha } from './fecha';
import type { MontoEntrada } from './montoEntrada';
import type { Uuid } from './uuid';

/**
 * Datos de un traslado de fondos entre dos cuentas de efectivo o bancos (ADR-041 §5.3). Ambas cuentas deben ser de detalle, activas, del grupo 1101 (422 CON-022) y distintas entre sí.
 */
export interface TrasladoSolicitud {
  /** Fecha contable del traslado; obligatoria y no futura (CON-007). */
  fecha: Fecha;
  /**
     * Descripción del traslado; forma parte del concepto del asiento.
     * @minLength 1
     * @maxLength 300
     */
  descripcion: string;
  /** Monto trasladado. */
  monto: MontoEntrada;
  /** Cuenta de detalle del grupo 1101 de donde sale el traslado (CON-006, CON-022). */
  cuentaOrigenId: Uuid;
  /** Cuenta de detalle del grupo 1101 a donde llega el traslado; distinta de cuentaOrigenId (CON-006, CON-022). */
  cuentaDestinoId: Uuid;
}
