/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { LineaVistaPrevia } from './lineaVistaPrevia';
import type { ModoPrecio } from './modoPrecio';
import type { Monto } from './monto';
import type { MontoConSigno } from './montoConSigno';

/**
 * Resultado de expandir y sumar un asiento sin guardarlo. Se devuelve aunque no cuadre (ADR-036), para validar la partida doble sobre las líneas expandidas por el backend.
 */
export interface VistaPreviaAsiento {
  /** Modo de precio aplicado; nulo si ninguna línea lleva IVA. */
  modoPrecio: ModoPrecio | null;
  /**
     * Tasa de IVA vigente a la fecha del asiento como cadena decimal; nula si ninguna línea lleva IVA.
     * @nullable
     * @pattern ^\d{1,3}(\.\d{1,4})?$
     */
  tasaIva: string | null;
  /** Líneas expandidas, con las de IVA calculado incluidas. */
  lineas: LineaVistaPrevia[];
  totalDebe: Monto;
  totalHaber: Monto;
  /** Σ Debe − Σ Haber de las líneas expandidas. */
  diferencia: MontoConSigno;
  /** true si hay al menos dos líneas, los totales son mayores que cero y el Debe es igual al Haber. */
  cuadra: boolean;
}
