/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import type { LineaVistaPrevia } from './lineaVistaPrevia';
import type { Monto } from './monto';
import type { MontoConSigno } from './montoConSigno';
import type { ResumenOperacionGuiada } from './resumenOperacionGuiada';

/**
 * Resultado de armar y sumar el asiento de una operación guiada sin guardarlo (patrón de ADR-036). Se devuelve aunque no cuadre; solo responde 422 si los datos no se pueden expandir.
 */
export interface VistaPreviaOperacion {
  /** Líneas del asiento que se generaría. */
  lineas: LineaVistaPrevia[];
  totalDebe: Monto;
  totalHaber: Monto;
  /** Σ Debe − Σ Haber de las líneas. */
  diferencia: MontoConSigno;
  /** true si hay al menos dos líneas, los totales son mayores que cero y el Debe es igual al Haber. */
  cuadra: boolean;
  resumen: ResumenOperacionGuiada;
}
