/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AplicacionCatalogo,
  DemasiadasPeticionesResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  NoEncontradoResponse,
  ProhibidoResponse
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listarAplicacionesResponse200 = {
  data: AplicacionCatalogo[]
  status: 200
}

export type listarAplicacionesResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type listarAplicacionesResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type listarAplicacionesResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type listarAplicacionesResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type listarAplicacionesResponseSuccess = (listarAplicacionesResponse200) & {
  headers: Headers;
};
export type listarAplicacionesResponseError = (listarAplicacionesResponse401 | listarAplicacionesResponse403 | listarAplicacionesResponse429 | listarAplicacionesResponse500) & {
  headers: Headers;
};

export type listarAplicacionesResponse = (listarAplicacionesResponseSuccess | listarAplicacionesResponseError)

export const getListarAplicacionesUrl = () => {




  return `/aplicaciones`
}

/**
 * Devuelve el catálogo completo de apps, ordenado por el orden del catálogo, con su estado para la empresa activa: INSTALADA, DISPONIBLE (comunitaria aún no instalada) o BLOQUEADA_ENTERPRISE. No se pagina porque el catálogo es corto y global. Rol mínimo: auditor (cualquier miembro activo).
 * @summary Catálogo de apps con su estado para la empresa activa
 */
export const listarAplicaciones = async ( options?: Parameters<typeof clienteHttp>[1]): Promise<listarAplicacionesResponse> => {

  return clienteHttp<listarAplicacionesResponse>(getListarAplicacionesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarAplicacionesQueryKey = () => {
    return [
    `/aplicaciones`
    ] as const;
    }


export const getListarAplicacionesQueryOptions = <TData = Awaited<ReturnType<typeof listarAplicaciones>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAplicaciones>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarAplicacionesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarAplicaciones>>> = ({ signal }) => listarAplicaciones({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarAplicaciones>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarAplicacionesQueryResult = NonNullable<Awaited<ReturnType<typeof listarAplicaciones>>>
export type ListarAplicacionesQueryError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useListarAplicaciones<TData = Awaited<ReturnType<typeof listarAplicaciones>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAplicaciones>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarAplicaciones>>,
          TError,
          Awaited<ReturnType<typeof listarAplicaciones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarAplicaciones<TData = Awaited<ReturnType<typeof listarAplicaciones>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAplicaciones>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarAplicaciones>>,
          TError,
          Awaited<ReturnType<typeof listarAplicaciones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarAplicaciones<TData = Awaited<ReturnType<typeof listarAplicaciones>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAplicaciones>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Catálogo de apps con su estado para la empresa activa
 */

export function useListarAplicaciones<TData = Awaited<ReturnType<typeof listarAplicaciones>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAplicaciones>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarAplicacionesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type instalarAplicacionResponse200 = {
  data: AplicacionCatalogo
  status: 200
}

export type instalarAplicacionResponse201 = {
  data: AplicacionCatalogo
  status: 201
}

export type instalarAplicacionResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type instalarAplicacionResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type instalarAplicacionResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type instalarAplicacionResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type instalarAplicacionResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type instalarAplicacionResponseSuccess = (instalarAplicacionResponse200 | instalarAplicacionResponse201) & {
  headers: Headers;
};
export type instalarAplicacionResponseError = (instalarAplicacionResponse401 | instalarAplicacionResponse403 | instalarAplicacionResponse404 | instalarAplicacionResponse429 | instalarAplicacionResponse500) & {
  headers: Headers;
};

export type instalarAplicacionResponse = (instalarAplicacionResponseSuccess | instalarAplicacionResponseError)

export const getInstalarAplicacionUrl = (codigo: string,) => {




  return `/aplicaciones/${codigo}/instalacion`
}

/**
 * Instala la app indicada y ejecuta su precarga en la misma transacción; si la precarga falla, la instalación se revierte. Responde 201 si la instaló ahora y 200 si ya estaba instalada. No existe desinstalación en 1.0. Las apps Enterprise no se pueden instalar (403 PLT-011). Rol mínimo: admin_empresa.
 * @summary Instala una app comunitaria en la empresa activa
 */
export const instalarAplicacion = async (codigo: string, options?: Parameters<typeof clienteHttp>[1]): Promise<instalarAplicacionResponse> => {

  return clienteHttp<instalarAplicacionResponse>(getInstalarAplicacionUrl(codigo),
  {
    ...options,
    method: 'POST'


  }
);}





export const getInstalarAplicacionQueryKey = (codigo: string,) => {
    return [
    'POST', `/aplicaciones/${codigo}/instalacion`
    ] as const;
    }


export const getInstalarAplicacionQueryOptions = <TData = Awaited<ReturnType<typeof instalarAplicacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(codigo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof instalarAplicacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInstalarAplicacionQueryKey(codigo);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof instalarAplicacion>>> = ({ signal }) => instalarAplicacion(codigo, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: codigo !== null && codigo !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof instalarAplicacion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InstalarAplicacionQueryResult = NonNullable<Awaited<ReturnType<typeof instalarAplicacion>>>
export type InstalarAplicacionQueryError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useInstalarAplicacion<TData = Awaited<ReturnType<typeof instalarAplicacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 codigo: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof instalarAplicacion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof instalarAplicacion>>,
          TError,
          Awaited<ReturnType<typeof instalarAplicacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInstalarAplicacion<TData = Awaited<ReturnType<typeof instalarAplicacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 codigo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof instalarAplicacion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof instalarAplicacion>>,
          TError,
          Awaited<ReturnType<typeof instalarAplicacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInstalarAplicacion<TData = Awaited<ReturnType<typeof instalarAplicacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 codigo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof instalarAplicacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Instala una app comunitaria en la empresa activa
 */

export function useInstalarAplicacion<TData = Awaited<ReturnType<typeof instalarAplicacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 codigo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof instalarAplicacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInstalarAplicacionQueryOptions(codigo,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






