/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Asiento,
  ConflictoResponse,
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  ListarAsientosParams,
  NoAutenticadoResponse,
  NoEncontradoResponse,
  NuevaReversion,
  NuevoAsiento,
  PaginaAsientos,
  PrecondicionRequeridaResponse,
  ProhibidoResponse,
  SolicitudInvalidaResponse,
  VistaPreviaAsiento
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type registrarAsientoResponse201 = {
  data: Asiento
  status: 201
}

export type registrarAsientoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarAsientoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarAsientoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarAsientoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarAsientoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarAsientoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarAsientoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarAsientoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarAsientoResponseSuccess = (registrarAsientoResponse201) & {
  headers: Headers;
};
export type registrarAsientoResponseError = (registrarAsientoResponse400 | registrarAsientoResponse401 | registrarAsientoResponse403 | registrarAsientoResponse409 | registrarAsientoResponse422 | registrarAsientoResponse428 | registrarAsientoResponse429 | registrarAsientoResponse500) & {
  headers: Headers;
};

export type registrarAsientoResponse = (registrarAsientoResponseSuccess | registrarAsientoResponseError)

export const getRegistrarAsientoUrl = () => {




  return `/contabilidad/asientos`
}

/**
 * Registra un asiento manual del Libro Diario en una sola transacción: expande el IVA de las líneas que lo llevan (CLAUDE.md §11.2), valida la partida doble, asigna el número correlativo, guarda cabecera y líneas y mayoriza los saldos (ADR-018); o se guarda todo o no se guarda nada. Exige Idempotency-Key: repetir la misma clave con el mismo cuerpo devuelve la respuesta original con Idempotency-Replayed true. Un asiento guardado es inmutable (ADR-019). Rol mínimo: contador.
 * @summary Registra un asiento manual
 */
export const registrarAsiento = async (nuevoAsiento: NuevoAsiento, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarAsientoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarAsientoResponse>(getRegistrarAsientoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nuevoAsiento)
  }
);}





export const getRegistrarAsientoQueryKey = (nuevoAsiento?: NuevoAsiento,) => {
    return [
    'POST', `/contabilidad/asientos`, nuevoAsiento
    ] as const;
    }


export const getRegistrarAsientoQueryOptions = <TData = Awaited<ReturnType<typeof registrarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarAsientoQueryKey(nuevoAsiento);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarAsiento>>> = ({ signal }) => registrarAsiento(nuevoAsiento, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarAsiento>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarAsientoQueryResult = NonNullable<Awaited<ReturnType<typeof registrarAsiento>>>
export type RegistrarAsientoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarAsiento<TData = Awaited<ReturnType<typeof registrarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAsiento>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarAsiento>>,
          TError,
          Awaited<ReturnType<typeof registrarAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarAsiento<TData = Awaited<ReturnType<typeof registrarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAsiento>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarAsiento>>,
          TError,
          Awaited<ReturnType<typeof registrarAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarAsiento<TData = Awaited<ReturnType<typeof registrarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra un asiento manual
 */

export function useRegistrarAsiento<TData = Awaited<ReturnType<typeof registrarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarAsientoQueryOptions(nuevoAsiento,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listarAsientosResponse200 = {
  data: PaginaAsientos
  status: 200
}

export type listarAsientosResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type listarAsientosResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type listarAsientosResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type listarAsientosResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type listarAsientosResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type listarAsientosResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type listarAsientosResponseSuccess = (listarAsientosResponse200) & {
  headers: Headers;
};
export type listarAsientosResponseError = (listarAsientosResponse400 | listarAsientosResponse401 | listarAsientosResponse403 | listarAsientosResponse422 | listarAsientosResponse429 | listarAsientosResponse500) & {
  headers: Headers;
};

export type listarAsientosResponse = (listarAsientosResponseSuccess | listarAsientosResponseError)

export const getListarAsientosUrl = (params?: ListarAsientosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/asientos?${stringifiedParams}` : `/contabilidad/asientos`
}

/**
 * Lista los asientos de la empresa (Libro Diario) paginados por cursor y ordenados por año y número ascendentes. Los filtros son opcionales y se combinan: desde y hasta (fecha contable, ambos inclusive), anio, numero, origen, estado y cuentaId (asientos con alguna línea en esa cuenta). El listado devuelve el resumen sin líneas; el detalle está en la consulta individual. Rol mínimo: auditor.
 * @summary Libro Diario paginado
 */
export const listarAsientos = async (params?: ListarAsientosParams, options?: Parameters<typeof clienteHttp>[1]): Promise<listarAsientosResponse> => {

  return clienteHttp<listarAsientosResponse>(getListarAsientosUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarAsientosQueryKey = (params?: ListarAsientosParams,) => {
    return [
    `/contabilidad/asientos`, ...(params ? [params] : [])
    ] as const;
    }


export const getListarAsientosQueryOptions = <TData = Awaited<ReturnType<typeof listarAsientos>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params?: ListarAsientosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAsientos>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarAsientosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarAsientos>>> = ({ signal }) => listarAsientos(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarAsientos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarAsientosQueryResult = NonNullable<Awaited<ReturnType<typeof listarAsientos>>>
export type ListarAsientosQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useListarAsientos<TData = Awaited<ReturnType<typeof listarAsientos>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: undefined |  ListarAsientosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAsientos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarAsientos>>,
          TError,
          Awaited<ReturnType<typeof listarAsientos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarAsientos<TData = Awaited<ReturnType<typeof listarAsientos>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarAsientosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAsientos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarAsientos>>,
          TError,
          Awaited<ReturnType<typeof listarAsientos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarAsientos<TData = Awaited<ReturnType<typeof listarAsientos>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarAsientosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAsientos>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Libro Diario paginado
 */

export function useListarAsientos<TData = Awaited<ReturnType<typeof listarAsientos>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarAsientosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarAsientos>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarAsientosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarAsientoResponse200 = {
  data: VistaPreviaAsiento
  status: 200
}

export type previsualizarAsientoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarAsientoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarAsientoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarAsientoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarAsientoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarAsientoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarAsientoResponseSuccess = (previsualizarAsientoResponse200) & {
  headers: Headers;
};
export type previsualizarAsientoResponseError = (previsualizarAsientoResponse400 | previsualizarAsientoResponse401 | previsualizarAsientoResponse403 | previsualizarAsientoResponse422 | previsualizarAsientoResponse429 | previsualizarAsientoResponse500) & {
  headers: Headers;
};

export type previsualizarAsientoResponse = (previsualizarAsientoResponseSuccess | previsualizarAsientoResponseError)

export const getPrevisualizarAsientoUrl = () => {




  return `/contabilidad/asientos/vista-previa`
}

/**
 * Expande el IVA de las líneas que lo llevan y calcula los totales y la diferencia sin guardar nada ni numerar el asiento; no exige Idempotency-Key. Responde 200 aunque el asiento no cuadre (cuadra false y diferencia distinta de cero, ADR-036), para que el frontend valide la partida doble sobre las líneas expandidas por el backend. Solo responde 422 si no se puede expandir. Rol mínimo: contador.
 * @summary Vista previa de un asiento sin guardarlo
 */
export const previsualizarAsiento = async (nuevoAsiento: NuevoAsiento, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarAsientoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarAsientoResponse>(getPrevisualizarAsientoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nuevoAsiento)
  }
);}





export const getPrevisualizarAsientoQueryKey = (nuevoAsiento?: NuevoAsiento,) => {
    return [
    'POST', `/contabilidad/asientos/vista-previa`, nuevoAsiento
    ] as const;
    }


export const getPrevisualizarAsientoQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarAsientoQueryKey(nuevoAsiento);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarAsiento>>> = ({ signal }) => previsualizarAsiento(nuevoAsiento, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarAsiento>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarAsientoQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarAsiento>>>
export type PrevisualizarAsientoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarAsiento<TData = Awaited<ReturnType<typeof previsualizarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAsiento>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarAsiento>>,
          TError,
          Awaited<ReturnType<typeof previsualizarAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarAsiento<TData = Awaited<ReturnType<typeof previsualizarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAsiento>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarAsiento>>,
          TError,
          Awaited<ReturnType<typeof previsualizarAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarAsiento<TData = Awaited<ReturnType<typeof previsualizarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de un asiento sin guardarlo
 */

export function usePrevisualizarAsiento<TData = Awaited<ReturnType<typeof previsualizarAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevoAsiento: NuevoAsiento, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarAsientoQueryOptions(nuevoAsiento,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type obtenerAsientoResponse200 = {
  data: Asiento
  status: 200
}

export type obtenerAsientoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerAsientoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerAsientoResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type obtenerAsientoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerAsientoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerAsientoResponseSuccess = (obtenerAsientoResponse200) & {
  headers: Headers;
};
export type obtenerAsientoResponseError = (obtenerAsientoResponse401 | obtenerAsientoResponse403 | obtenerAsientoResponse404 | obtenerAsientoResponse429 | obtenerAsientoResponse500) & {
  headers: Headers;
};

export type obtenerAsientoResponse = (obtenerAsientoResponseSuccess | obtenerAsientoResponseError)

export const getObtenerAsientoUrl = (asientoId: string,) => {




  return `/contabilidad/asientos/${asientoId}`
}

/**
 * Devuelve un asiento con todas sus líneas. No lleva ETag porque un asiento guardado es inmutable salvo su paso a REVERTIDO (ADR-019). Rol mínimo: auditor.
 * @summary Consulta un asiento con sus líneas
 */
export const obtenerAsiento = async (asientoId: string, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerAsientoResponse> => {

  return clienteHttp<obtenerAsientoResponse>(getObtenerAsientoUrl(asientoId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerAsientoQueryKey = (asientoId: string,) => {
    return [
    `/contabilidad/asientos/${asientoId}`
    ] as const;
    }


export const getObtenerAsientoQueryOptions = <TData = Awaited<ReturnType<typeof obtenerAsiento>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(asientoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerAsientoQueryKey(asientoId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerAsiento>>> = ({ signal }) => obtenerAsiento(asientoId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: asientoId !== null && asientoId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerAsiento>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerAsientoQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerAsiento>>>
export type ObtenerAsientoQueryError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerAsiento<TData = Awaited<ReturnType<typeof obtenerAsiento>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAsiento>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerAsiento>>,
          TError,
          Awaited<ReturnType<typeof obtenerAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerAsiento<TData = Awaited<ReturnType<typeof obtenerAsiento>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAsiento>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerAsiento>>,
          TError,
          Awaited<ReturnType<typeof obtenerAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerAsiento<TData = Awaited<ReturnType<typeof obtenerAsiento>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Consulta un asiento con sus líneas
 */

export function useObtenerAsiento<TData = Awaited<ReturnType<typeof obtenerAsiento>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerAsientoQueryOptions(asientoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type revertirAsientoResponse201 = {
  data: Asiento
  status: 201
}

export type revertirAsientoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type revertirAsientoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type revertirAsientoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type revertirAsientoResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type revertirAsientoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type revertirAsientoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type revertirAsientoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type revertirAsientoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type revertirAsientoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type revertirAsientoResponseSuccess = (revertirAsientoResponse201) & {
  headers: Headers;
};
export type revertirAsientoResponseError = (revertirAsientoResponse400 | revertirAsientoResponse401 | revertirAsientoResponse403 | revertirAsientoResponse404 | revertirAsientoResponse409 | revertirAsientoResponse422 | revertirAsientoResponse428 | revertirAsientoResponse429 | revertirAsientoResponse500) & {
  headers: Headers;
};

export type revertirAsientoResponse = (revertirAsientoResponseSuccess | revertirAsientoResponseError)

export const getRevertirAsientoUrl = (asientoId: string,) => {




  return `/contabilidad/asientos/${asientoId}/reversion`
}

/**
 * Crea un asiento de reversión con el Debe y el Haber intercambiados, concepto fijo "Reversión del asiento N.º <numero>/<anio>" y estado CONTABILIZADO, y marca el original como REVERTIDO; mayoriza igual que cualquier asiento, así que los saldos vuelven a su valor anterior (CLAUDE.md §10.1, ADR-019, ADR-036). La fecha es opcional (por defecto hoy en hora de El Salvador); no puede ser futura ni anterior a la del asiento original. Un asiento ya revertido o una reversión no pueden revertirse. Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Revierte un asiento
 */
export const revertirAsiento = async (asientoId: string,
    nuevaReversion?: NuevaReversion, options?: Parameters<typeof clienteHttp>[1]): Promise<revertirAsientoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<revertirAsientoResponse>(getRevertirAsientoUrl(asientoId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nuevaReversion)
  }
);}





export const getRevertirAsientoQueryKey = (asientoId: string,
    nuevaReversion?: NuevaReversion,) => {
    return [
    'POST', `/contabilidad/asientos/${asientoId}/reversion`, nuevaReversion
    ] as const;
    }


export const getRevertirAsientoQueryOptions = <TData = Awaited<ReturnType<typeof revertirAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(asientoId: string,
    nuevaReversion?: NuevaReversion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revertirAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRevertirAsientoQueryKey(asientoId,nuevaReversion);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof revertirAsiento>>> = ({ signal }) => revertirAsiento(asientoId,nuevaReversion, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: asientoId !== null && asientoId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof revertirAsiento>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RevertirAsientoQueryResult = NonNullable<Awaited<ReturnType<typeof revertirAsiento>>>
export type RevertirAsientoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRevertirAsiento<TData = Awaited<ReturnType<typeof revertirAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string,
    nuevaReversion: undefined |  NuevaReversion, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof revertirAsiento>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof revertirAsiento>>,
          TError,
          Awaited<ReturnType<typeof revertirAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRevertirAsiento<TData = Awaited<ReturnType<typeof revertirAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string,
    nuevaReversion?: NuevaReversion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revertirAsiento>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof revertirAsiento>>,
          TError,
          Awaited<ReturnType<typeof revertirAsiento>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRevertirAsiento<TData = Awaited<ReturnType<typeof revertirAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string,
    nuevaReversion?: NuevaReversion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revertirAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Revierte un asiento
 */

export function useRevertirAsiento<TData = Awaited<ReturnType<typeof revertirAsiento>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 asientoId: string,
    nuevaReversion?: NuevaReversion, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revertirAsiento>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRevertirAsientoQueryOptions(asientoId,nuevaReversion,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






