/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CobroClienteSolicitud,
  ConflictoResponse,
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  OperacionRegistrada,
  PrecondicionRequeridaResponse,
  ProhibidoResponse,
  SolicitudInvalidaResponse,
  VentaSolicitud,
  VistaPreviaOperacion
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type registrarVentaResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarVentaResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarVentaResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarVentaResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarVentaResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarVentaResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarVentaResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarVentaResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarVentaResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarVentaResponseSuccess = (registrarVentaResponse201) & {
  headers: Headers;
};
export type registrarVentaResponseError = (registrarVentaResponse400 | registrarVentaResponse401 | registrarVentaResponse403 | registrarVentaResponse409 | registrarVentaResponse422 | registrarVentaResponse428 | registrarVentaResponse429 | registrarVentaResponse500) & {
  headers: Headers;
};

export type registrarVentaResponse = (registrarVentaResponseSuccess | registrarVentaResponseError)

export const getRegistrarVentaUrl = () => {




  return `/contabilidad/operaciones/ventas`
}

/**
 * Registra una venta en una sola transacción: arma el asiento con la forma de cobro al Debe y las ventas gravadas, exentas y no sujetas más el IVA débito fiscal al Haber (ADR-041 §5.3), valida la partida doble, numera, guarda, mayoriza y audita (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra una venta
 */
export const registrarVenta = async (ventaSolicitud: VentaSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarVentaResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarVentaResponse>(getRegistrarVentaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(ventaSolicitud)
  }
);}





export const getRegistrarVentaQueryKey = (ventaSolicitud?: VentaSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/ventas`, ventaSolicitud
    ] as const;
    }


export const getRegistrarVentaQueryOptions = <TData = Awaited<ReturnType<typeof registrarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarVenta>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarVentaQueryKey(ventaSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarVenta>>> = ({ signal }) => registrarVenta(ventaSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarVenta>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarVentaQueryResult = NonNullable<Awaited<ReturnType<typeof registrarVenta>>>
export type RegistrarVentaQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarVenta<TData = Awaited<ReturnType<typeof registrarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarVenta>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarVenta>>,
          TError,
          Awaited<ReturnType<typeof registrarVenta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarVenta<TData = Awaited<ReturnType<typeof registrarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarVenta>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarVenta>>,
          TError,
          Awaited<ReturnType<typeof registrarVenta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarVenta<TData = Awaited<ReturnType<typeof registrarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarVenta>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra una venta
 */

export function useRegistrarVenta<TData = Awaited<ReturnType<typeof registrarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarVenta>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarVentaQueryOptions(ventaSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarVentaResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarVentaResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarVentaResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarVentaResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarVentaResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarVentaResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarVentaResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarVentaResponseSuccess = (previsualizarVentaResponse200) & {
  headers: Headers;
};
export type previsualizarVentaResponseError = (previsualizarVentaResponse400 | previsualizarVentaResponse401 | previsualizarVentaResponse403 | previsualizarVentaResponse422 | previsualizarVentaResponse429 | previsualizarVentaResponse500) & {
  headers: Headers;
};

export type previsualizarVentaResponse = (previsualizarVentaResponseSuccess | previsualizarVentaResponseError)

export const getPrevisualizarVentaUrl = () => {




  return `/contabilidad/operaciones/ventas/vista-previa`
}

/**
 * Arma el asiento de una venta y calcula sus totales sin guardar nada (patrón ADR-036). Rol mínimo: contador.
 * @summary Vista previa de una venta sin guardarla
 */
export const previsualizarVenta = async (ventaSolicitud: VentaSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarVentaResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarVentaResponse>(getPrevisualizarVentaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(ventaSolicitud)
  }
);}





export const getPrevisualizarVentaQueryKey = (ventaSolicitud?: VentaSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/ventas/vista-previa`, ventaSolicitud
    ] as const;
    }


export const getPrevisualizarVentaQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarVenta>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarVentaQueryKey(ventaSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarVenta>>> = ({ signal }) => previsualizarVenta(ventaSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarVenta>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarVentaQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarVenta>>>
export type PrevisualizarVentaQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarVenta<TData = Awaited<ReturnType<typeof previsualizarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarVenta>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarVenta>>,
          TError,
          Awaited<ReturnType<typeof previsualizarVenta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarVenta<TData = Awaited<ReturnType<typeof previsualizarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarVenta>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarVenta>>,
          TError,
          Awaited<ReturnType<typeof previsualizarVenta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarVenta<TData = Awaited<ReturnType<typeof previsualizarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarVenta>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de una venta sin guardarla
 */

export function usePrevisualizarVenta<TData = Awaited<ReturnType<typeof previsualizarVenta>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 ventaSolicitud: VentaSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarVenta>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarVentaQueryOptions(ventaSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registrarCobroClienteResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarCobroClienteResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarCobroClienteResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarCobroClienteResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarCobroClienteResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarCobroClienteResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarCobroClienteResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarCobroClienteResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarCobroClienteResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarCobroClienteResponseSuccess = (registrarCobroClienteResponse201) & {
  headers: Headers;
};
export type registrarCobroClienteResponseError = (registrarCobroClienteResponse400 | registrarCobroClienteResponse401 | registrarCobroClienteResponse403 | registrarCobroClienteResponse409 | registrarCobroClienteResponse422 | registrarCobroClienteResponse428 | registrarCobroClienteResponse429 | registrarCobroClienteResponse500) & {
  headers: Headers;
};

export type registrarCobroClienteResponse = (registrarCobroClienteResponseSuccess | registrarCobroClienteResponseError)

export const getRegistrarCobroClienteUrl = () => {




  return `/contabilidad/operaciones/cobros`
}

/**
 * Registra el cobro a un cliente, por su cartera o por la liquidación de un emisor de tarjetas (ADR-041 §5.3), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra un cobro a un cliente
 */
export const registrarCobroCliente = async (cobroClienteSolicitud: CobroClienteSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarCobroClienteResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarCobroClienteResponse>(getRegistrarCobroClienteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cobroClienteSolicitud)
  }
);}





export const getRegistrarCobroClienteQueryKey = (cobroClienteSolicitud?: CobroClienteSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/cobros`, cobroClienteSolicitud
    ] as const;
    }


export const getRegistrarCobroClienteQueryOptions = <TData = Awaited<ReturnType<typeof registrarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCobroCliente>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarCobroClienteQueryKey(cobroClienteSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarCobroCliente>>> = ({ signal }) => registrarCobroCliente(cobroClienteSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarCobroCliente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarCobroClienteQueryResult = NonNullable<Awaited<ReturnType<typeof registrarCobroCliente>>>
export type RegistrarCobroClienteQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarCobroCliente<TData = Awaited<ReturnType<typeof registrarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCobroCliente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarCobroCliente>>,
          TError,
          Awaited<ReturnType<typeof registrarCobroCliente>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarCobroCliente<TData = Awaited<ReturnType<typeof registrarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCobroCliente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarCobroCliente>>,
          TError,
          Awaited<ReturnType<typeof registrarCobroCliente>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarCobroCliente<TData = Awaited<ReturnType<typeof registrarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCobroCliente>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra un cobro a un cliente
 */

export function useRegistrarCobroCliente<TData = Awaited<ReturnType<typeof registrarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCobroCliente>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarCobroClienteQueryOptions(cobroClienteSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarCobroClienteResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarCobroClienteResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarCobroClienteResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarCobroClienteResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarCobroClienteResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarCobroClienteResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarCobroClienteResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarCobroClienteResponseSuccess = (previsualizarCobroClienteResponse200) & {
  headers: Headers;
};
export type previsualizarCobroClienteResponseError = (previsualizarCobroClienteResponse400 | previsualizarCobroClienteResponse401 | previsualizarCobroClienteResponse403 | previsualizarCobroClienteResponse422 | previsualizarCobroClienteResponse429 | previsualizarCobroClienteResponse500) & {
  headers: Headers;
};

export type previsualizarCobroClienteResponse = (previsualizarCobroClienteResponseSuccess | previsualizarCobroClienteResponseError)

export const getPrevisualizarCobroClienteUrl = () => {




  return `/contabilidad/operaciones/cobros/vista-previa`
}

/**
 * Arma el asiento de un cobro a un cliente y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de un cobro a un cliente sin guardarlo
 */
export const previsualizarCobroCliente = async (cobroClienteSolicitud: CobroClienteSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarCobroClienteResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarCobroClienteResponse>(getPrevisualizarCobroClienteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cobroClienteSolicitud)
  }
);}





export const getPrevisualizarCobroClienteQueryKey = (cobroClienteSolicitud?: CobroClienteSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/cobros/vista-previa`, cobroClienteSolicitud
    ] as const;
    }


export const getPrevisualizarCobroClienteQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarCobroClienteQueryKey(cobroClienteSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarCobroCliente>>> = ({ signal }) => previsualizarCobroCliente(cobroClienteSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarCobroClienteQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarCobroCliente>>>
export type PrevisualizarCobroClienteQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarCobroCliente<TData = Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarCobroCliente>>,
          TError,
          Awaited<ReturnType<typeof previsualizarCobroCliente>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarCobroCliente<TData = Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarCobroCliente>>,
          TError,
          Awaited<ReturnType<typeof previsualizarCobroCliente>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarCobroCliente<TData = Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de un cobro a un cliente sin guardarlo
 */

export function usePrevisualizarCobroCliente<TData = Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 cobroClienteSolicitud: CobroClienteSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCobroCliente>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarCobroClienteQueryOptions(cobroClienteSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






