/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActualizacionEmpresa,
  DemasiadasPeticionesResponse,
  Empresa,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  NoEncontradoResponse,
  PrecondicionFallidaResponse,
  PrecondicionRequeridaResponse,
  ProhibidoResponse,
  SolicitudInvalidaResponse
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type obtenerEmpresaResponse200 = {
  data: Empresa
  status: 200
}

export type obtenerEmpresaResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerEmpresaResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerEmpresaResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type obtenerEmpresaResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerEmpresaResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerEmpresaResponseSuccess = (obtenerEmpresaResponse200) & {
  headers: Headers;
};
export type obtenerEmpresaResponseError = (obtenerEmpresaResponse401 | obtenerEmpresaResponse403 | obtenerEmpresaResponse404 | obtenerEmpresaResponse429 | obtenerEmpresaResponse500) & {
  headers: Headers;
};

export type obtenerEmpresaResponse = (obtenerEmpresaResponseSuccess | obtenerEmpresaResponseError)

export const getObtenerEmpresaUrl = (empresaId: string,) => {




  return `/empresas/${empresaId}`
}

/**
 * Devuelve la empresa activa. {empresaId} debe ser igual a X-Empresa-Id; si no lo es, responde 404 PLT-017 para no revelar la existencia de otras empresas. La respuesta trae el header ETag con la versión actual, que debe enviarse como If-Match al editar. Rol mínimo: admin_empresa.
 * @summary Consulta la empresa activa
 */
export const obtenerEmpresa = async (empresaId: string, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerEmpresaResponse> => {

  return clienteHttp<obtenerEmpresaResponse>(getObtenerEmpresaUrl(empresaId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerEmpresaQueryKey = (empresaId: string,) => {
    return [
    `/empresas/${empresaId}`
    ] as const;
    }


export const getObtenerEmpresaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerEmpresa>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(empresaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEmpresa>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerEmpresaQueryKey(empresaId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerEmpresa>>> = ({ signal }) => obtenerEmpresa(empresaId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: empresaId !== null && empresaId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerEmpresa>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerEmpresaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerEmpresa>>>
export type ObtenerEmpresaQueryError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerEmpresa<TData = Awaited<ReturnType<typeof obtenerEmpresa>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEmpresa>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEmpresa>>,
          TError,
          Awaited<ReturnType<typeof obtenerEmpresa>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEmpresa<TData = Awaited<ReturnType<typeof obtenerEmpresa>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEmpresa>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEmpresa>>,
          TError,
          Awaited<ReturnType<typeof obtenerEmpresa>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEmpresa<TData = Awaited<ReturnType<typeof obtenerEmpresa>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEmpresa>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Consulta la empresa activa
 */

export function useObtenerEmpresa<TData = Awaited<ReturnType<typeof obtenerEmpresa>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEmpresa>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerEmpresaQueryOptions(empresaId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type actualizarEmpresaResponse200 = {
  data: Empresa
  status: 200
}

export type actualizarEmpresaResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type actualizarEmpresaResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type actualizarEmpresaResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type actualizarEmpresaResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type actualizarEmpresaResponse412 = {
  data: PrecondicionFallidaResponse
  status: 412
}

export type actualizarEmpresaResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type actualizarEmpresaResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type actualizarEmpresaResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type actualizarEmpresaResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type actualizarEmpresaResponseSuccess = (actualizarEmpresaResponse200) & {
  headers: Headers;
};
export type actualizarEmpresaResponseError = (actualizarEmpresaResponse400 | actualizarEmpresaResponse401 | actualizarEmpresaResponse403 | actualizarEmpresaResponse404 | actualizarEmpresaResponse412 | actualizarEmpresaResponse422 | actualizarEmpresaResponse428 | actualizarEmpresaResponse429 | actualizarEmpresaResponse500) & {
  headers: Headers;
};

export type actualizarEmpresaResponse = (actualizarEmpresaResponseSuccess | actualizarEmpresaResponseError)

export const getActualizarEmpresaUrl = (empresaId: string,) => {




  return `/empresas/${empresaId}`
}

/**
 * Cambia el nombre del espacio de trabajo (empresa activa). Es lo único editable en la versión abierta: los usuarios son personas naturales y no se capturan datos empresariales (ADR-031, ADR-032); cada app guarda su propia configuración. Exige If-Match con el ETag leído (concurrencia optimista) y devuelve el nuevo ETag. {empresaId} debe ser igual a X-Empresa-Id; si no, 404 PLT-017. Rol mínimo: admin_empresa.
 * @summary Edita la empresa activa
 */
export const actualizarEmpresa = async (empresaId: string,
    actualizacionEmpresa: ActualizacionEmpresa, options?: Parameters<typeof clienteHttp>[1]): Promise<actualizarEmpresaResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<actualizarEmpresaResponse>(getActualizarEmpresaUrl(empresaId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(actualizacionEmpresa)
  }
);}





export const getActualizarEmpresaQueryKey = (empresaId: string,
    actualizacionEmpresa?: ActualizacionEmpresa,) => {
    return [
    'PATCH', `/empresas/${empresaId}`, actualizacionEmpresa
    ] as const;
    }


export const getActualizarEmpresaQueryOptions = <TData = Awaited<ReturnType<typeof actualizarEmpresa>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(empresaId: string,
    actualizacionEmpresa: ActualizacionEmpresa, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarEmpresa>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActualizarEmpresaQueryKey(empresaId,actualizacionEmpresa);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof actualizarEmpresa>>> = ({ signal }) => actualizarEmpresa(empresaId,actualizacionEmpresa, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: empresaId !== null && empresaId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof actualizarEmpresa>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActualizarEmpresaQueryResult = NonNullable<Awaited<ReturnType<typeof actualizarEmpresa>>>
export type ActualizarEmpresaQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useActualizarEmpresa<TData = Awaited<ReturnType<typeof actualizarEmpresa>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string,
    actualizacionEmpresa: ActualizacionEmpresa, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarEmpresa>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof actualizarEmpresa>>,
          TError,
          Awaited<ReturnType<typeof actualizarEmpresa>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActualizarEmpresa<TData = Awaited<ReturnType<typeof actualizarEmpresa>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string,
    actualizacionEmpresa: ActualizacionEmpresa, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarEmpresa>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof actualizarEmpresa>>,
          TError,
          Awaited<ReturnType<typeof actualizarEmpresa>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActualizarEmpresa<TData = Awaited<ReturnType<typeof actualizarEmpresa>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string,
    actualizacionEmpresa: ActualizacionEmpresa, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarEmpresa>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Edita la empresa activa
 */

export function useActualizarEmpresa<TData = Awaited<ReturnType<typeof actualizarEmpresa>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | PrecondicionFallidaResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 empresaId: string,
    actualizacionEmpresa: ActualizacionEmpresa, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof actualizarEmpresa>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActualizarEmpresaQueryOptions(empresaId,actualizacionEmpresa,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






