/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  ObtenerTableroParams,
  ProhibidoResponse,
  SolicitudInvalidaResponse,
  Tablero
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type obtenerTableroResponse200 = {
  data: Tablero
  status: 200
}

export type obtenerTableroResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type obtenerTableroResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerTableroResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerTableroResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type obtenerTableroResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerTableroResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerTableroResponseSuccess = (obtenerTableroResponse200) & {
  headers: Headers;
};
export type obtenerTableroResponseError = (obtenerTableroResponse400 | obtenerTableroResponse401 | obtenerTableroResponse403 | obtenerTableroResponse422 | obtenerTableroResponse429 | obtenerTableroResponse500) & {
  headers: Headers;
};

export type obtenerTableroResponse = (obtenerTableroResponseSuccess | obtenerTableroResponseError)

export const getObtenerTableroUrl = (params: ObtenerTableroParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/tablero?${stringifiedParams}` : `/contabilidad/tablero`
}

/**
 * Devuelve los indicadores y los pendientes accionables del mes indicado: efectivo por cuenta, por cobrar, por pagar, resultado del mes y del anterior, IVA estimado, la serie de los últimos 6 meses y los pendientes de contabilidad (ADR-041 §5.7). Rol mínimo: auditor.
 * @summary Consulta el tablero de inicio
 */
export const obtenerTablero = async (params: ObtenerTableroParams, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerTableroResponse> => {

  return clienteHttp<obtenerTableroResponse>(getObtenerTableroUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerTableroQueryKey = (params?: ObtenerTableroParams,) => {
    return [
    `/contabilidad/tablero`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerTableroQueryOptions = <TData = Awaited<ReturnType<typeof obtenerTablero>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params: ObtenerTableroParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerTablero>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerTableroQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerTablero>>> = ({ signal }) => obtenerTablero(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerTablero>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerTableroQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerTablero>>>
export type ObtenerTableroQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerTablero<TData = Awaited<ReturnType<typeof obtenerTablero>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerTableroParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerTablero>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerTablero>>,
          TError,
          Awaited<ReturnType<typeof obtenerTablero>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerTablero<TData = Awaited<ReturnType<typeof obtenerTablero>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerTableroParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerTablero>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerTablero>>,
          TError,
          Awaited<ReturnType<typeof obtenerTablero>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerTablero<TData = Awaited<ReturnType<typeof obtenerTablero>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerTableroParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerTablero>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Consulta el tablero de inicio
 */

export function useObtenerTablero<TData = Awaited<ReturnType<typeof obtenerTablero>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerTableroParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerTablero>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerTableroQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






