/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DemasiadasPeticionesResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  UsuarioActual
} from '../modelos';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type obtenerUsuarioActualResponse200 = {
  data: UsuarioActual
  status: 200
}

export type obtenerUsuarioActualResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerUsuarioActualResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerUsuarioActualResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerUsuarioActualResponseSuccess = (obtenerUsuarioActualResponse200) & {
  headers: Headers;
};
export type obtenerUsuarioActualResponseError = (obtenerUsuarioActualResponse401 | obtenerUsuarioActualResponse429 | obtenerUsuarioActualResponse500) & {
  headers: Headers;
};

export type obtenerUsuarioActualResponse = (obtenerUsuarioActualResponseSuccess | obtenerUsuarioActualResponseError)

export const getObtenerUsuarioActualUrl = () => {




  return `/me`
}

/**
 * Implementado en F1. Devuelve el usuario autenticado y las empresas a las que pertenece con su rol en cada una. No requiere el header X-Empresa-Id porque se usa justamente para elegir la empresa activa.
 * @summary Usuario actual y sus membresías
 */
export const obtenerUsuarioActual = async ( options?: RequestInit): Promise<obtenerUsuarioActualResponse> => {

  const res = await fetch(getObtenerUsuarioActualUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: obtenerUsuarioActualResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as obtenerUsuarioActualResponse
}





export const getObtenerUsuarioActualQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getObtenerUsuarioActualQueryOptions = <TData = Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError = NoAutenticadoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerUsuarioActualQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerUsuarioActual>>> = ({ signal }) => obtenerUsuarioActual({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerUsuarioActualQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerUsuarioActual>>>
export type ObtenerUsuarioActualQueryError = NoAutenticadoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerUsuarioActual<TData = Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError = NoAutenticadoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerUsuarioActual>>,
          TError,
          Awaited<ReturnType<typeof obtenerUsuarioActual>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerUsuarioActual<TData = Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError = NoAutenticadoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerUsuarioActual>>,
          TError,
          Awaited<ReturnType<typeof obtenerUsuarioActual>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerUsuarioActual<TData = Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError = NoAutenticadoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Usuario actual y sus membresías
 */

export function useObtenerUsuarioActual<TData = Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError = NoAutenticadoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerUsuarioActual>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerUsuarioActualQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






