/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompraGastoSolicitud,
  ConflictoResponse,
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  OperacionRegistrada,
  PagoProveedorSolicitud,
  PrecondicionRequeridaResponse,
  ProhibidoResponse,
  SolicitudInvalidaResponse,
  VistaPreviaOperacion
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type registrarCompraGastoResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarCompraGastoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarCompraGastoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarCompraGastoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarCompraGastoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarCompraGastoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarCompraGastoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarCompraGastoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarCompraGastoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarCompraGastoResponseSuccess = (registrarCompraGastoResponse201) & {
  headers: Headers;
};
export type registrarCompraGastoResponseError = (registrarCompraGastoResponse400 | registrarCompraGastoResponse401 | registrarCompraGastoResponse403 | registrarCompraGastoResponse409 | registrarCompraGastoResponse422 | registrarCompraGastoResponse428 | registrarCompraGastoResponse429 | registrarCompraGastoResponse500) & {
  headers: Headers;
};

export type registrarCompraGastoResponse = (registrarCompraGastoResponseSuccess | registrarCompraGastoResponseError)

export const getRegistrarCompraGastoUrl = () => {




  return `/contabilidad/operaciones/compras-gastos`
}

/**
 * Registra una compra o un gasto por su destino y su documento (ADR-041 §5.3, §5.4), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra una compra o un gasto
 */
export const registrarCompraGasto = async (compraGastoSolicitud: CompraGastoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarCompraGastoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarCompraGastoResponse>(getRegistrarCompraGastoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(compraGastoSolicitud)
  }
);}





export const getRegistrarCompraGastoQueryKey = (compraGastoSolicitud?: CompraGastoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/compras-gastos`, compraGastoSolicitud
    ] as const;
    }


export const getRegistrarCompraGastoQueryOptions = <TData = Awaited<ReturnType<typeof registrarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCompraGasto>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarCompraGastoQueryKey(compraGastoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarCompraGasto>>> = ({ signal }) => registrarCompraGasto(compraGastoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarCompraGasto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarCompraGastoQueryResult = NonNullable<Awaited<ReturnType<typeof registrarCompraGasto>>>
export type RegistrarCompraGastoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarCompraGasto<TData = Awaited<ReturnType<typeof registrarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCompraGasto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarCompraGasto>>,
          TError,
          Awaited<ReturnType<typeof registrarCompraGasto>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarCompraGasto<TData = Awaited<ReturnType<typeof registrarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCompraGasto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarCompraGasto>>,
          TError,
          Awaited<ReturnType<typeof registrarCompraGasto>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarCompraGasto<TData = Awaited<ReturnType<typeof registrarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCompraGasto>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra una compra o un gasto
 */

export function useRegistrarCompraGasto<TData = Awaited<ReturnType<typeof registrarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarCompraGasto>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarCompraGastoQueryOptions(compraGastoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarCompraGastoResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarCompraGastoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarCompraGastoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarCompraGastoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarCompraGastoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarCompraGastoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarCompraGastoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarCompraGastoResponseSuccess = (previsualizarCompraGastoResponse200) & {
  headers: Headers;
};
export type previsualizarCompraGastoResponseError = (previsualizarCompraGastoResponse400 | previsualizarCompraGastoResponse401 | previsualizarCompraGastoResponse403 | previsualizarCompraGastoResponse422 | previsualizarCompraGastoResponse429 | previsualizarCompraGastoResponse500) & {
  headers: Headers;
};

export type previsualizarCompraGastoResponse = (previsualizarCompraGastoResponseSuccess | previsualizarCompraGastoResponseError)

export const getPrevisualizarCompraGastoUrl = () => {




  return `/contabilidad/operaciones/compras-gastos/vista-previa`
}

/**
 * Arma el asiento de una compra o un gasto y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de una compra o un gasto sin guardarlo
 */
export const previsualizarCompraGasto = async (compraGastoSolicitud: CompraGastoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarCompraGastoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarCompraGastoResponse>(getPrevisualizarCompraGastoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(compraGastoSolicitud)
  }
);}





export const getPrevisualizarCompraGastoQueryKey = (compraGastoSolicitud?: CompraGastoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/compras-gastos/vista-previa`, compraGastoSolicitud
    ] as const;
    }


export const getPrevisualizarCompraGastoQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarCompraGastoQueryKey(compraGastoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarCompraGasto>>> = ({ signal }) => previsualizarCompraGasto(compraGastoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarCompraGastoQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarCompraGasto>>>
export type PrevisualizarCompraGastoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarCompraGasto<TData = Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarCompraGasto>>,
          TError,
          Awaited<ReturnType<typeof previsualizarCompraGasto>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarCompraGasto<TData = Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarCompraGasto>>,
          TError,
          Awaited<ReturnType<typeof previsualizarCompraGasto>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarCompraGasto<TData = Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de una compra o un gasto sin guardarlo
 */

export function usePrevisualizarCompraGasto<TData = Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 compraGastoSolicitud: CompraGastoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarCompraGasto>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarCompraGastoQueryOptions(compraGastoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registrarPagoProveedorResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarPagoProveedorResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarPagoProveedorResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarPagoProveedorResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarPagoProveedorResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarPagoProveedorResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarPagoProveedorResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarPagoProveedorResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarPagoProveedorResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarPagoProveedorResponseSuccess = (registrarPagoProveedorResponse201) & {
  headers: Headers;
};
export type registrarPagoProveedorResponseError = (registrarPagoProveedorResponse400 | registrarPagoProveedorResponse401 | registrarPagoProveedorResponse403 | registrarPagoProveedorResponse409 | registrarPagoProveedorResponse422 | registrarPagoProveedorResponse428 | registrarPagoProveedorResponse429 | registrarPagoProveedorResponse500) & {
  headers: Headers;
};

export type registrarPagoProveedorResponse = (registrarPagoProveedorResponseSuccess | registrarPagoProveedorResponseError)

export const getRegistrarPagoProveedorUrl = () => {




  return `/contabilidad/operaciones/pagos-proveedores`
}

/**
 * Registra un pago a proveedor, debitando la cartera de proveedores (ADR-041 §5.3), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra un pago a proveedor
 */
export const registrarPagoProveedor = async (pagoProveedorSolicitud: PagoProveedorSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarPagoProveedorResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarPagoProveedorResponse>(getRegistrarPagoProveedorUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pagoProveedorSolicitud)
  }
);}





export const getRegistrarPagoProveedorQueryKey = (pagoProveedorSolicitud?: PagoProveedorSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/pagos-proveedores`, pagoProveedorSolicitud
    ] as const;
    }


export const getRegistrarPagoProveedorQueryOptions = <TData = Awaited<ReturnType<typeof registrarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPagoProveedor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarPagoProveedorQueryKey(pagoProveedorSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarPagoProveedor>>> = ({ signal }) => registrarPagoProveedor(pagoProveedorSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarPagoProveedor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarPagoProveedorQueryResult = NonNullable<Awaited<ReturnType<typeof registrarPagoProveedor>>>
export type RegistrarPagoProveedorQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarPagoProveedor<TData = Awaited<ReturnType<typeof registrarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPagoProveedor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarPagoProveedor>>,
          TError,
          Awaited<ReturnType<typeof registrarPagoProveedor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarPagoProveedor<TData = Awaited<ReturnType<typeof registrarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPagoProveedor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarPagoProveedor>>,
          TError,
          Awaited<ReturnType<typeof registrarPagoProveedor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarPagoProveedor<TData = Awaited<ReturnType<typeof registrarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPagoProveedor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra un pago a proveedor
 */

export function useRegistrarPagoProveedor<TData = Awaited<ReturnType<typeof registrarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarPagoProveedor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarPagoProveedorQueryOptions(pagoProveedorSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarPagoProveedorResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarPagoProveedorResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarPagoProveedorResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarPagoProveedorResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarPagoProveedorResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarPagoProveedorResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarPagoProveedorResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarPagoProveedorResponseSuccess = (previsualizarPagoProveedorResponse200) & {
  headers: Headers;
};
export type previsualizarPagoProveedorResponseError = (previsualizarPagoProveedorResponse400 | previsualizarPagoProveedorResponse401 | previsualizarPagoProveedorResponse403 | previsualizarPagoProveedorResponse422 | previsualizarPagoProveedorResponse429 | previsualizarPagoProveedorResponse500) & {
  headers: Headers;
};

export type previsualizarPagoProveedorResponse = (previsualizarPagoProveedorResponseSuccess | previsualizarPagoProveedorResponseError)

export const getPrevisualizarPagoProveedorUrl = () => {




  return `/contabilidad/operaciones/pagos-proveedores/vista-previa`
}

/**
 * Arma el asiento de un pago a proveedor y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de un pago a proveedor sin guardarlo
 */
export const previsualizarPagoProveedor = async (pagoProveedorSolicitud: PagoProveedorSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarPagoProveedorResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarPagoProveedorResponse>(getPrevisualizarPagoProveedorUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pagoProveedorSolicitud)
  }
);}





export const getPrevisualizarPagoProveedorQueryKey = (pagoProveedorSolicitud?: PagoProveedorSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/pagos-proveedores/vista-previa`, pagoProveedorSolicitud
    ] as const;
    }


export const getPrevisualizarPagoProveedorQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarPagoProveedorQueryKey(pagoProveedorSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarPagoProveedor>>> = ({ signal }) => previsualizarPagoProveedor(pagoProveedorSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarPagoProveedorQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarPagoProveedor>>>
export type PrevisualizarPagoProveedorQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarPagoProveedor<TData = Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarPagoProveedor>>,
          TError,
          Awaited<ReturnType<typeof previsualizarPagoProveedor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarPagoProveedor<TData = Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarPagoProveedor>>,
          TError,
          Awaited<ReturnType<typeof previsualizarPagoProveedor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarPagoProveedor<TData = Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de un pago a proveedor sin guardarlo
 */

export function usePrevisualizarPagoProveedor<TData = Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 pagoProveedorSolicitud: PagoProveedorSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarPagoProveedor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarPagoProveedorQueryOptions(pagoProveedorSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






