/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiKeyCreada,
  DemasiadasPeticionesResponse,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  ListarApiKeysParams,
  NoAutenticadoResponse,
  NoEncontradoResponse,
  NuevaApiKey,
  PaginaApiKeys,
  ProhibidoResponse,
  SolicitudInvalidaResponse
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listarApiKeysResponse200 = {
  data: PaginaApiKeys
  status: 200
}

export type listarApiKeysResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type listarApiKeysResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type listarApiKeysResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type listarApiKeysResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type listarApiKeysResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type listarApiKeysResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type listarApiKeysResponseSuccess = (listarApiKeysResponse200) & {
  headers: Headers;
};
export type listarApiKeysResponseError = (listarApiKeysResponse400 | listarApiKeysResponse401 | listarApiKeysResponse403 | listarApiKeysResponse422 | listarApiKeysResponse429 | listarApiKeysResponse500) & {
  headers: Headers;
};

export type listarApiKeysResponse = (listarApiKeysResponseSuccess | listarApiKeysResponseError)

export const getListarApiKeysUrl = (params?: ListarApiKeysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api-keys?${stringifiedParams}` : `/api-keys`
}

/**
 * Lista paginada por cursor de las API keys de la empresa activa, incluidas las revocadas. Nunca devuelve el secreto ni su hash. Rol mínimo: admin_empresa.
 * @summary Lista las API keys de la empresa
 */
export const listarApiKeys = async (params?: ListarApiKeysParams, options?: Parameters<typeof clienteHttp>[1]): Promise<listarApiKeysResponse> => {

  return clienteHttp<listarApiKeysResponse>(getListarApiKeysUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarApiKeysQueryKey = (params?: ListarApiKeysParams,) => {
    return [
    `/api-keys`, ...(params ? [params] : [])
    ] as const;
    }


export const getListarApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof listarApiKeys>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params?: ListarApiKeysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarApiKeys>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarApiKeysQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarApiKeys>>> = ({ signal }) => listarApiKeys(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarApiKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof listarApiKeys>>>
export type ListarApiKeysQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useListarApiKeys<TData = Awaited<ReturnType<typeof listarApiKeys>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: undefined |  ListarApiKeysParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarApiKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarApiKeys>>,
          TError,
          Awaited<ReturnType<typeof listarApiKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarApiKeys<TData = Awaited<ReturnType<typeof listarApiKeys>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarApiKeysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarApiKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarApiKeys>>,
          TError,
          Awaited<ReturnType<typeof listarApiKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarApiKeys<TData = Awaited<ReturnType<typeof listarApiKeys>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarApiKeysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarApiKeys>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista las API keys de la empresa
 */

export function useListarApiKeys<TData = Awaited<ReturnType<typeof listarApiKeys>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params?: ListarApiKeysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarApiKeys>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarApiKeysQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type crearApiKeyResponse201 = {
  data: ApiKeyCreada
  status: 201
}

export type crearApiKeyResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type crearApiKeyResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type crearApiKeyResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type crearApiKeyResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type crearApiKeyResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type crearApiKeyResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type crearApiKeyResponseSuccess = (crearApiKeyResponse201) & {
  headers: Headers;
};
export type crearApiKeyResponseError = (crearApiKeyResponse400 | crearApiKeyResponse401 | crearApiKeyResponse403 | crearApiKeyResponse422 | crearApiKeyResponse429 | crearApiKeyResponse500) & {
  headers: Headers;
};

export type crearApiKeyResponse = (crearApiKeyResponseSuccess | crearApiKeyResponseError)

export const getCrearApiKeyUrl = () => {




  return `/api-keys`
}

/**
 * Crea una API key con los alcances indicados. El secreto completo (pk_xxxx.secreto) se muestra una sola vez en esta respuesta y no se puede recuperar después; el servidor guarda solo su hash Argon2id. Rol mínimo: admin_empresa.
 * @summary Crea una API key
 */
export const crearApiKey = async (nuevaApiKey: NuevaApiKey, options?: Parameters<typeof clienteHttp>[1]): Promise<crearApiKeyResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<crearApiKeyResponse>(getCrearApiKeyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(nuevaApiKey)
  }
);}





export const getCrearApiKeyQueryKey = (nuevaApiKey?: NuevaApiKey,) => {
    return [
    'POST', `/api-keys`, nuevaApiKey
    ] as const;
    }


export const getCrearApiKeyQueryOptions = <TData = Awaited<ReturnType<typeof crearApiKey>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(nuevaApiKey: NuevaApiKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crearApiKey>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCrearApiKeyQueryKey(nuevaApiKey);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof crearApiKey>>> = ({ signal }) => crearApiKey(nuevaApiKey, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof crearApiKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CrearApiKeyQueryResult = NonNullable<Awaited<ReturnType<typeof crearApiKey>>>
export type CrearApiKeyQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useCrearApiKey<TData = Awaited<ReturnType<typeof crearApiKey>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevaApiKey: NuevaApiKey, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof crearApiKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof crearApiKey>>,
          TError,
          Awaited<ReturnType<typeof crearApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCrearApiKey<TData = Awaited<ReturnType<typeof crearApiKey>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevaApiKey: NuevaApiKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crearApiKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof crearApiKey>>,
          TError,
          Awaited<ReturnType<typeof crearApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCrearApiKey<TData = Awaited<ReturnType<typeof crearApiKey>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevaApiKey: NuevaApiKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crearApiKey>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Crea una API key
 */

export function useCrearApiKey<TData = Awaited<ReturnType<typeof crearApiKey>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 nuevaApiKey: NuevaApiKey, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof crearApiKey>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCrearApiKeyQueryOptions(nuevaApiKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type revocarApiKeyResponse204 = {
  data: void
  status: 204
}

export type revocarApiKeyResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type revocarApiKeyResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type revocarApiKeyResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type revocarApiKeyResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type revocarApiKeyResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type revocarApiKeyResponseSuccess = (revocarApiKeyResponse204) & {
  headers: Headers;
};
export type revocarApiKeyResponseError = (revocarApiKeyResponse401 | revocarApiKeyResponse403 | revocarApiKeyResponse404 | revocarApiKeyResponse429 | revocarApiKeyResponse500) & {
  headers: Headers;
};

export type revocarApiKeyResponse = (revocarApiKeyResponseSuccess | revocarApiKeyResponseError)

export const getRevocarApiKeyUrl = (apiKeyId: string,) => {




  return `/api-keys/${apiKeyId}`
}

/**
 * Revoca la API key de forma definitiva. Es idempotente: revocar una clave ya revocada también responde 204. Rol mínimo: admin_empresa.
 * @summary Revoca una API key
 */
export const revocarApiKey = async (apiKeyId: string, options?: Parameters<typeof clienteHttp>[1]): Promise<revocarApiKeyResponse> => {

  return clienteHttp<revocarApiKeyResponse>(getRevocarApiKeyUrl(apiKeyId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRevocarApiKeyQueryKey = (apiKeyId: string,) => {
    return [
    'DELETE', `/api-keys/${apiKeyId}`
    ] as const;
    }


export const getRevocarApiKeyQueryOptions = <TData = Awaited<ReturnType<typeof revocarApiKey>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(apiKeyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revocarApiKey>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRevocarApiKeyQueryKey(apiKeyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof revocarApiKey>>> = ({ signal }) => revocarApiKey(apiKeyId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: apiKeyId !== null && apiKeyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof revocarApiKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RevocarApiKeyQueryResult = NonNullable<Awaited<ReturnType<typeof revocarApiKey>>>
export type RevocarApiKeyQueryError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRevocarApiKey<TData = Awaited<ReturnType<typeof revocarApiKey>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 apiKeyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof revocarApiKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof revocarApiKey>>,
          TError,
          Awaited<ReturnType<typeof revocarApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRevocarApiKey<TData = Awaited<ReturnType<typeof revocarApiKey>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 apiKeyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revocarApiKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof revocarApiKey>>,
          TError,
          Awaited<ReturnType<typeof revocarApiKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRevocarApiKey<TData = Awaited<ReturnType<typeof revocarApiKey>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 apiKeyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revocarApiKey>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Revoca una API key
 */

export function useRevocarApiKey<TData = Awaited<ReturnType<typeof revocarApiKey>>, TError = NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 apiKeyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof revocarApiKey>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRevocarApiKeyQueryOptions(apiKeyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






