/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivoFijo,
  ActivoFijoSolicitud,
  ConflictoResponse,
  DemasiadasPeticionesResponse,
  DepreciacionSolicitud,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  NoAutenticadoResponse,
  OperacionRegistrada,
  PrecondicionRequeridaResponse,
  ProhibidoResponse,
  SolicitudInvalidaResponse,
  VistaPreviaOperacion
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type registrarActivoFijoResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarActivoFijoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarActivoFijoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarActivoFijoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarActivoFijoResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarActivoFijoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarActivoFijoResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarActivoFijoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarActivoFijoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarActivoFijoResponseSuccess = (registrarActivoFijoResponse201) & {
  headers: Headers;
};
export type registrarActivoFijoResponseError = (registrarActivoFijoResponse400 | registrarActivoFijoResponse401 | registrarActivoFijoResponse403 | registrarActivoFijoResponse409 | registrarActivoFijoResponse422 | registrarActivoFijoResponse428 | registrarActivoFijoResponse429 | registrarActivoFijoResponse500) & {
  headers: Headers;
};

export type registrarActivoFijoResponse = (registrarActivoFijoResponseSuccess | registrarActivoFijoResponseError)

export const getRegistrarActivoFijoUrl = () => {




  return `/contabilidad/operaciones/activos-fijos`
}

/**
 * Registra la compra de un activo fijo: da de alta el activo y contabiliza su costo (ADR-041 §5.5), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra la compra de un activo fijo
 */
export const registrarActivoFijo = async (activoFijoSolicitud: ActivoFijoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarActivoFijoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarActivoFijoResponse>(getRegistrarActivoFijoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(activoFijoSolicitud)
  }
);}





export const getRegistrarActivoFijoQueryKey = (activoFijoSolicitud?: ActivoFijoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/activos-fijos`, activoFijoSolicitud
    ] as const;
    }


export const getRegistrarActivoFijoQueryOptions = <TData = Awaited<ReturnType<typeof registrarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarActivoFijo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarActivoFijoQueryKey(activoFijoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarActivoFijo>>> = ({ signal }) => registrarActivoFijo(activoFijoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarActivoFijo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarActivoFijoQueryResult = NonNullable<Awaited<ReturnType<typeof registrarActivoFijo>>>
export type RegistrarActivoFijoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarActivoFijo<TData = Awaited<ReturnType<typeof registrarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarActivoFijo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarActivoFijo>>,
          TError,
          Awaited<ReturnType<typeof registrarActivoFijo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarActivoFijo<TData = Awaited<ReturnType<typeof registrarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarActivoFijo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarActivoFijo>>,
          TError,
          Awaited<ReturnType<typeof registrarActivoFijo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarActivoFijo<TData = Awaited<ReturnType<typeof registrarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarActivoFijo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra la compra de un activo fijo
 */

export function useRegistrarActivoFijo<TData = Awaited<ReturnType<typeof registrarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarActivoFijo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarActivoFijoQueryOptions(activoFijoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarActivoFijoResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarActivoFijoResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarActivoFijoResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarActivoFijoResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarActivoFijoResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarActivoFijoResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarActivoFijoResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarActivoFijoResponseSuccess = (previsualizarActivoFijoResponse200) & {
  headers: Headers;
};
export type previsualizarActivoFijoResponseError = (previsualizarActivoFijoResponse400 | previsualizarActivoFijoResponse401 | previsualizarActivoFijoResponse403 | previsualizarActivoFijoResponse422 | previsualizarActivoFijoResponse429 | previsualizarActivoFijoResponse500) & {
  headers: Headers;
};

export type previsualizarActivoFijoResponse = (previsualizarActivoFijoResponseSuccess | previsualizarActivoFijoResponseError)

export const getPrevisualizarActivoFijoUrl = () => {




  return `/contabilidad/operaciones/activos-fijos/vista-previa`
}

/**
 * Arma el asiento de la compra de un activo fijo y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de la compra de un activo fijo sin guardarlo
 */
export const previsualizarActivoFijo = async (activoFijoSolicitud: ActivoFijoSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarActivoFijoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarActivoFijoResponse>(getPrevisualizarActivoFijoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(activoFijoSolicitud)
  }
);}





export const getPrevisualizarActivoFijoQueryKey = (activoFijoSolicitud?: ActivoFijoSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/activos-fijos/vista-previa`, activoFijoSolicitud
    ] as const;
    }


export const getPrevisualizarActivoFijoQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarActivoFijoQueryKey(activoFijoSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarActivoFijo>>> = ({ signal }) => previsualizarActivoFijo(activoFijoSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarActivoFijoQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarActivoFijo>>>
export type PrevisualizarActivoFijoQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarActivoFijo<TData = Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarActivoFijo>>,
          TError,
          Awaited<ReturnType<typeof previsualizarActivoFijo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarActivoFijo<TData = Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarActivoFijo>>,
          TError,
          Awaited<ReturnType<typeof previsualizarActivoFijo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarActivoFijo<TData = Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de la compra de un activo fijo sin guardarlo
 */

export function usePrevisualizarActivoFijo<TData = Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 activoFijoSolicitud: ActivoFijoSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarActivoFijo>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarActivoFijoQueryOptions(activoFijoSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type registrarDepreciacionResponse201 = {
  data: OperacionRegistrada
  status: 201
}

export type registrarDepreciacionResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type registrarDepreciacionResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type registrarDepreciacionResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type registrarDepreciacionResponse409 = {
  data: ConflictoResponse
  status: 409
}

export type registrarDepreciacionResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type registrarDepreciacionResponse428 = {
  data: PrecondicionRequeridaResponse
  status: 428
}

export type registrarDepreciacionResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type registrarDepreciacionResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type registrarDepreciacionResponseSuccess = (registrarDepreciacionResponse201) & {
  headers: Headers;
};
export type registrarDepreciacionResponseError = (registrarDepreciacionResponse400 | registrarDepreciacionResponse401 | registrarDepreciacionResponse403 | registrarDepreciacionResponse409 | registrarDepreciacionResponse422 | registrarDepreciacionResponse428 | registrarDepreciacionResponse429 | registrarDepreciacionResponse500) & {
  headers: Headers;
};

export type registrarDepreciacionResponse = (registrarDepreciacionResponseSuccess | registrarDepreciacionResponseError)

export const getRegistrarDepreciacionUrl = () => {




  return `/contabilidad/operaciones/depreciaciones`
}

/**
 * Registra la depreciación del mes: por cada categoría con activos vigentes calcula la cuota en línea recta y genera su asiento, una sola vez por activo y mes (ADR-041 §5.5), en la misma transacción de guardado, mayorización y auditoría (ADR-018). Bloqueada con CON-023 mientras la vida útil de alguna categoría con activos no esté confirmada por el contador. Exige Idempotency-Key. Rol mínimo: contador.
 * @summary Registra la depreciación mensual
 */
export const registrarDepreciacion = async (depreciacionSolicitud: DepreciacionSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<registrarDepreciacionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<registrarDepreciacionResponse>(getRegistrarDepreciacionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(depreciacionSolicitud)
  }
);}





export const getRegistrarDepreciacionQueryKey = (depreciacionSolicitud?: DepreciacionSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/depreciaciones`, depreciacionSolicitud
    ] as const;
    }


export const getRegistrarDepreciacionQueryOptions = <TData = Awaited<ReturnType<typeof registrarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarDepreciacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegistrarDepreciacionQueryKey(depreciacionSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registrarDepreciacion>>> = ({ signal }) => registrarDepreciacion(depreciacionSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registrarDepreciacion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RegistrarDepreciacionQueryResult = NonNullable<Awaited<ReturnType<typeof registrarDepreciacion>>>
export type RegistrarDepreciacionQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useRegistrarDepreciacion<TData = Awaited<ReturnType<typeof registrarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarDepreciacion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarDepreciacion>>,
          TError,
          Awaited<ReturnType<typeof registrarDepreciacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarDepreciacion<TData = Awaited<ReturnType<typeof registrarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarDepreciacion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof registrarDepreciacion>>,
          TError,
          Awaited<ReturnType<typeof registrarDepreciacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRegistrarDepreciacion<TData = Awaited<ReturnType<typeof registrarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarDepreciacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Registra la depreciación mensual
 */

export function useRegistrarDepreciacion<TData = Awaited<ReturnType<typeof registrarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | ConflictoResponse | EntidadNoProcesableResponse | PrecondicionRequeridaResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof registrarDepreciacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRegistrarDepreciacionQueryOptions(depreciacionSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type previsualizarDepreciacionResponse200 = {
  data: VistaPreviaOperacion
  status: 200
}

export type previsualizarDepreciacionResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type previsualizarDepreciacionResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type previsualizarDepreciacionResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type previsualizarDepreciacionResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type previsualizarDepreciacionResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type previsualizarDepreciacionResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type previsualizarDepreciacionResponseSuccess = (previsualizarDepreciacionResponse200) & {
  headers: Headers;
};
export type previsualizarDepreciacionResponseError = (previsualizarDepreciacionResponse400 | previsualizarDepreciacionResponse401 | previsualizarDepreciacionResponse403 | previsualizarDepreciacionResponse422 | previsualizarDepreciacionResponse429 | previsualizarDepreciacionResponse500) & {
  headers: Headers;
};

export type previsualizarDepreciacionResponse = (previsualizarDepreciacionResponseSuccess | previsualizarDepreciacionResponseError)

export const getPrevisualizarDepreciacionUrl = () => {




  return `/contabilidad/operaciones/depreciaciones/vista-previa`
}

/**
 * Arma el asiento de la depreciación del mes y calcula sus totales sin guardar nada. Rol mínimo: contador.
 * @summary Vista previa de la depreciación mensual sin guardarla
 */
export const previsualizarDepreciacion = async (depreciacionSolicitud: DepreciacionSolicitud, options?: Parameters<typeof clienteHttp>[1]): Promise<previsualizarDepreciacionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return clienteHttp<previsualizarDepreciacionResponse>(getPrevisualizarDepreciacionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(depreciacionSolicitud)
  }
);}





export const getPrevisualizarDepreciacionQueryKey = (depreciacionSolicitud?: DepreciacionSolicitud,) => {
    return [
    'POST', `/contabilidad/operaciones/depreciaciones/vista-previa`, depreciacionSolicitud
    ] as const;
    }


export const getPrevisualizarDepreciacionQueryOptions = <TData = Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrevisualizarDepreciacionQueryKey(depreciacionSolicitud);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previsualizarDepreciacion>>> = ({ signal }) => previsualizarDepreciacion(depreciacionSolicitud, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrevisualizarDepreciacionQueryResult = NonNullable<Awaited<ReturnType<typeof previsualizarDepreciacion>>>
export type PrevisualizarDepreciacionQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function usePrevisualizarDepreciacion<TData = Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarDepreciacion>>,
          TError,
          Awaited<ReturnType<typeof previsualizarDepreciacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarDepreciacion<TData = Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previsualizarDepreciacion>>,
          TError,
          Awaited<ReturnType<typeof previsualizarDepreciacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrevisualizarDepreciacion<TData = Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vista previa de la depreciación mensual sin guardarla
 */

export function usePrevisualizarDepreciacion<TData = Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 depreciacionSolicitud: DepreciacionSolicitud, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previsualizarDepreciacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrevisualizarDepreciacionQueryOptions(depreciacionSolicitud,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listarActivosFijosResponse200 = {
  data: ActivoFijo[]
  status: 200
}

export type listarActivosFijosResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type listarActivosFijosResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type listarActivosFijosResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type listarActivosFijosResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type listarActivosFijosResponseSuccess = (listarActivosFijosResponse200) & {
  headers: Headers;
};
export type listarActivosFijosResponseError = (listarActivosFijosResponse401 | listarActivosFijosResponse403 | listarActivosFijosResponse429 | listarActivosFijosResponse500) & {
  headers: Headers;
};

export type listarActivosFijosResponse = (listarActivosFijosResponseSuccess | listarActivosFijosResponseError)

export const getListarActivosFijosUrl = () => {




  return `/contabilidad/activos-fijos`
}

/**
 * Devuelve los activos fijos de la empresa, sin paginar, con su depreciación acumulada y su valor en libros calculados al momento de la consulta (ADR-041 §5.5). Rol mínimo: auditor.
 * @summary Lista los activos fijos
 */
export const listarActivosFijos = async ( options?: Parameters<typeof clienteHttp>[1]): Promise<listarActivosFijosResponse> => {

  return clienteHttp<listarActivosFijosResponse>(getListarActivosFijosUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListarActivosFijosQueryKey = () => {
    return [
    `/contabilidad/activos-fijos`
    ] as const;
    }


export const getListarActivosFijosQueryOptions = <TData = Awaited<ReturnType<typeof listarActivosFijos>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarActivosFijos>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarActivosFijosQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarActivosFijos>>> = ({ signal }) => listarActivosFijos({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarActivosFijos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarActivosFijosQueryResult = NonNullable<Awaited<ReturnType<typeof listarActivosFijos>>>
export type ListarActivosFijosQueryError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useListarActivosFijos<TData = Awaited<ReturnType<typeof listarActivosFijos>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarActivosFijos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarActivosFijos>>,
          TError,
          Awaited<ReturnType<typeof listarActivosFijos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarActivosFijos<TData = Awaited<ReturnType<typeof listarActivosFijos>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarActivosFijos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarActivosFijos>>,
          TError,
          Awaited<ReturnType<typeof listarActivosFijos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarActivosFijos<TData = Awaited<ReturnType<typeof listarActivosFijos>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarActivosFijos>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista los activos fijos
 */

export function useListarActivosFijos<TData = Awaited<ReturnType<typeof listarActivosFijos>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarActivosFijos>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarActivosFijosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






