/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pilot API
 * API REST de Pilot, ERP multiempresa para PYMES de El Salvador. Incluye el núcleo (usuarios y empresas) y la app Contabilidad. Los montos viajan como cadena decimal con 2 decimales (ADR-013) y los errores siguen RFC 9457 (Problem Details).
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BalanzaComprobacion,
  DemasiadasPeticionesResponse,
  DiagnosticoMayorizacion,
  EntidadNoProcesableResponse,
  ErrorInternoResponse,
  EstadoResultados,
  EstadoSituacionFinanciera,
  LibroMayor,
  NoAutenticadoResponse,
  NoEncontradoResponse,
  ObtenerBalanzaParams,
  ObtenerEstadoResultadosParams,
  ObtenerEstadoSituacionFinancieraParams,
  ObtenerLibroMayorParams,
  ObtenerResumenIvaParams,
  ProhibidoResponse,
  ResumenIva,
  SolicitudInvalidaResponse
} from '../modelos';

import { clienteHttp } from '../../nucleo/http/clienteHttp';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type obtenerLibroMayorResponse200 = {
  data: LibroMayor
  status: 200
}

export type obtenerLibroMayorResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type obtenerLibroMayorResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerLibroMayorResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerLibroMayorResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type obtenerLibroMayorResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type obtenerLibroMayorResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerLibroMayorResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerLibroMayorResponseSuccess = (obtenerLibroMayorResponse200) & {
  headers: Headers;
};
export type obtenerLibroMayorResponseError = (obtenerLibroMayorResponse400 | obtenerLibroMayorResponse401 | obtenerLibroMayorResponse403 | obtenerLibroMayorResponse404 | obtenerLibroMayorResponse422 | obtenerLibroMayorResponse429 | obtenerLibroMayorResponse500) & {
  headers: Headers;
};

export type obtenerLibroMayorResponse = (obtenerLibroMayorResponseSuccess | obtenerLibroMayorResponseError)

export const getObtenerLibroMayorUrl = (params: ObtenerLibroMayorParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/mayor?${stringifiedParams}` : `/contabilidad/mayor`
}

/**
 * Devuelve el Libro Mayor de la cuenta indicada en el rango de fechas: saldo inicial, movimientos con saldo acumulado línea a línea, totales y saldo final. Acepta cualquier cuenta; en una cuenta padre, los movimientos son los de todas sus cuentas de detalle y cada línea identifica su propia cuenta (ADR-038 §5). Rol mínimo: auditor.
 * @summary Libro Mayor / auxiliar de una cuenta
 */
export const obtenerLibroMayor = async (params: ObtenerLibroMayorParams, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerLibroMayorResponse> => {

  return clienteHttp<obtenerLibroMayorResponse>(getObtenerLibroMayorUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerLibroMayorQueryKey = (params?: ObtenerLibroMayorParams,) => {
    return [
    `/contabilidad/mayor`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerLibroMayorQueryOptions = <TData = Awaited<ReturnType<typeof obtenerLibroMayor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params: ObtenerLibroMayorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerLibroMayor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerLibroMayorQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerLibroMayor>>> = ({ signal }) => obtenerLibroMayor(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerLibroMayor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerLibroMayorQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerLibroMayor>>>
export type ObtenerLibroMayorQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerLibroMayor<TData = Awaited<ReturnType<typeof obtenerLibroMayor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerLibroMayorParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerLibroMayor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerLibroMayor>>,
          TError,
          Awaited<ReturnType<typeof obtenerLibroMayor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerLibroMayor<TData = Awaited<ReturnType<typeof obtenerLibroMayor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerLibroMayorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerLibroMayor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerLibroMayor>>,
          TError,
          Awaited<ReturnType<typeof obtenerLibroMayor>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerLibroMayor<TData = Awaited<ReturnType<typeof obtenerLibroMayor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerLibroMayorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerLibroMayor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Libro Mayor / auxiliar de una cuenta
 */

export function useObtenerLibroMayor<TData = Awaited<ReturnType<typeof obtenerLibroMayor>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerLibroMayorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerLibroMayor>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerLibroMayorQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type obtenerBalanzaResponse200 = {
  data: BalanzaComprobacion
  status: 200
}

export type obtenerBalanzaResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type obtenerBalanzaResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerBalanzaResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerBalanzaResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type obtenerBalanzaResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerBalanzaResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerBalanzaResponseSuccess = (obtenerBalanzaResponse200) & {
  headers: Headers;
};
export type obtenerBalanzaResponseError = (obtenerBalanzaResponse400 | obtenerBalanzaResponse401 | obtenerBalanzaResponse403 | obtenerBalanzaResponse422 | obtenerBalanzaResponse429 | obtenerBalanzaResponse500) & {
  headers: Headers;
};

export type obtenerBalanzaResponse = (obtenerBalanzaResponseSuccess | obtenerBalanzaResponseError)

export const getObtenerBalanzaUrl = (params: ObtenerBalanzaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/balanza?${stringifiedParams}` : `/contabilidad/balanza`
}

/**
 * Devuelve la Balanza de Comprobación del rango de fechas con una fila por cuenta hasta el nivel pedido (1 a 5; 5 por defecto), con saldo inicial, Debe, Haber y saldo final. Los totales salen solo de las cuentas de detalle, para no contar dos veces los saldos de las cuentas padre (ADR-038 §6). Rol mínimo: auditor.
 * @summary Balanza de Comprobación
 */
export const obtenerBalanza = async (params: ObtenerBalanzaParams, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerBalanzaResponse> => {

  return clienteHttp<obtenerBalanzaResponse>(getObtenerBalanzaUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerBalanzaQueryKey = (params?: ObtenerBalanzaParams,) => {
    return [
    `/contabilidad/balanza`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerBalanzaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerBalanza>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params: ObtenerBalanzaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerBalanza>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerBalanzaQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerBalanza>>> = ({ signal }) => obtenerBalanza(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerBalanza>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerBalanzaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerBalanza>>>
export type ObtenerBalanzaQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerBalanza<TData = Awaited<ReturnType<typeof obtenerBalanza>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerBalanzaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerBalanza>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerBalanza>>,
          TError,
          Awaited<ReturnType<typeof obtenerBalanza>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerBalanza<TData = Awaited<ReturnType<typeof obtenerBalanza>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerBalanzaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerBalanza>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerBalanza>>,
          TError,
          Awaited<ReturnType<typeof obtenerBalanza>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerBalanza<TData = Awaited<ReturnType<typeof obtenerBalanza>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerBalanzaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerBalanza>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Balanza de Comprobación
 */

export function useObtenerBalanza<TData = Awaited<ReturnType<typeof obtenerBalanza>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerBalanzaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerBalanza>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerBalanzaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type obtenerEstadoSituacionFinancieraResponse200 = {
  data: EstadoSituacionFinanciera
  status: 200
}

export type obtenerEstadoSituacionFinancieraResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type obtenerEstadoSituacionFinancieraResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerEstadoSituacionFinancieraResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerEstadoSituacionFinancieraResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type obtenerEstadoSituacionFinancieraResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerEstadoSituacionFinancieraResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerEstadoSituacionFinancieraResponseSuccess = (obtenerEstadoSituacionFinancieraResponse200) & {
  headers: Headers;
};
export type obtenerEstadoSituacionFinancieraResponseError = (obtenerEstadoSituacionFinancieraResponse400 | obtenerEstadoSituacionFinancieraResponse401 | obtenerEstadoSituacionFinancieraResponse403 | obtenerEstadoSituacionFinancieraResponse422 | obtenerEstadoSituacionFinancieraResponse429 | obtenerEstadoSituacionFinancieraResponse500) & {
  headers: Headers;
};

export type obtenerEstadoSituacionFinancieraResponse = (obtenerEstadoSituacionFinancieraResponseSuccess | obtenerEstadoSituacionFinancieraResponseError)

export const getObtenerEstadoSituacionFinancieraUrl = (params: ObtenerEstadoSituacionFinancieraParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/estados/situacion-financiera?${stringifiedParams}` : `/contabilidad/estados/situacion-financiera`
}

/**
 * Devuelve el Estado de Situación Financiera de gestión a la fecha de corte pedida: Activo, Pasivo, Patrimonio, resultados de ejercicios anteriores no cerrados y utilidad del ejercicio, con la comprobación Activo = Pasivo + Patrimonio + resultados anteriores + utilidad del ejercicio (ADR-016) y su alerta si no cuadra (CLAUDE.md §10.4). Terminología NIIF para PYMES (ADR-037). Rol mínimo: auditor.
 * @summary Estado de Situación Financiera
 */
export const obtenerEstadoSituacionFinanciera = async (params: ObtenerEstadoSituacionFinancieraParams, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerEstadoSituacionFinancieraResponse> => {

  return clienteHttp<obtenerEstadoSituacionFinancieraResponse>(getObtenerEstadoSituacionFinancieraUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerEstadoSituacionFinancieraQueryKey = (params?: ObtenerEstadoSituacionFinancieraParams,) => {
    return [
    `/contabilidad/estados/situacion-financiera`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerEstadoSituacionFinancieraQueryOptions = <TData = Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params: ObtenerEstadoSituacionFinancieraParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerEstadoSituacionFinancieraQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>> = ({ signal }) => obtenerEstadoSituacionFinanciera(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerEstadoSituacionFinancieraQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>>
export type ObtenerEstadoSituacionFinancieraQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerEstadoSituacionFinanciera<TData = Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoSituacionFinancieraParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>,
          TError,
          Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEstadoSituacionFinanciera<TData = Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoSituacionFinancieraParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>,
          TError,
          Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEstadoSituacionFinanciera<TData = Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoSituacionFinancieraParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Estado de Situación Financiera
 */

export function useObtenerEstadoSituacionFinanciera<TData = Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoSituacionFinancieraParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoSituacionFinanciera>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerEstadoSituacionFinancieraQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type obtenerEstadoResultadosResponse200 = {
  data: EstadoResultados
  status: 200
}

export type obtenerEstadoResultadosResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type obtenerEstadoResultadosResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerEstadoResultadosResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerEstadoResultadosResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type obtenerEstadoResultadosResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerEstadoResultadosResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerEstadoResultadosResponseSuccess = (obtenerEstadoResultadosResponse200) & {
  headers: Headers;
};
export type obtenerEstadoResultadosResponseError = (obtenerEstadoResultadosResponse400 | obtenerEstadoResultadosResponse401 | obtenerEstadoResultadosResponse403 | obtenerEstadoResultadosResponse422 | obtenerEstadoResultadosResponse429 | obtenerEstadoResultadosResponse500) & {
  headers: Headers;
};

export type obtenerEstadoResultadosResponse = (obtenerEstadoResultadosResponseSuccess | obtenerEstadoResultadosResponseError)

export const getObtenerEstadoResultadosUrl = (params: ObtenerEstadoResultadosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/estados/resultados?${stringifiedParams}` : `/contabilidad/estados/resultados`
}

/**
 * Devuelve el Estado de Resultados de gestión del rango de fechas: ingresos, costos y gastos (sin el grupo 44), la utilidad antes de impuesto, el impuesto sobre la renta aparte y la utilidad del ejercicio (ADR-037). Rol mínimo: auditor.
 * @summary Estado de Resultados
 */
export const obtenerEstadoResultados = async (params: ObtenerEstadoResultadosParams, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerEstadoResultadosResponse> => {

  return clienteHttp<obtenerEstadoResultadosResponse>(getObtenerEstadoResultadosUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerEstadoResultadosQueryKey = (params?: ObtenerEstadoResultadosParams,) => {
    return [
    `/contabilidad/estados/resultados`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerEstadoResultadosQueryOptions = <TData = Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params: ObtenerEstadoResultadosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerEstadoResultadosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerEstadoResultados>>> = ({ signal }) => obtenerEstadoResultados(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerEstadoResultadosQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerEstadoResultados>>>
export type ObtenerEstadoResultadosQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerEstadoResultados<TData = Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoResultadosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEstadoResultados>>,
          TError,
          Awaited<ReturnType<typeof obtenerEstadoResultados>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEstadoResultados<TData = Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoResultadosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerEstadoResultados>>,
          TError,
          Awaited<ReturnType<typeof obtenerEstadoResultados>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerEstadoResultados<TData = Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoResultadosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Estado de Resultados
 */

export function useObtenerEstadoResultados<TData = Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerEstadoResultadosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerEstadoResultados>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerEstadoResultadosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type obtenerResumenIvaResponse200 = {
  data: ResumenIva
  status: 200
}

export type obtenerResumenIvaResponse400 = {
  data: SolicitudInvalidaResponse
  status: 400
}

export type obtenerResumenIvaResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type obtenerResumenIvaResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type obtenerResumenIvaResponse404 = {
  data: NoEncontradoResponse
  status: 404
}

export type obtenerResumenIvaResponse422 = {
  data: EntidadNoProcesableResponse
  status: 422
}

export type obtenerResumenIvaResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type obtenerResumenIvaResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type obtenerResumenIvaResponseSuccess = (obtenerResumenIvaResponse200) & {
  headers: Headers;
};
export type obtenerResumenIvaResponseError = (obtenerResumenIvaResponse400 | obtenerResumenIvaResponse401 | obtenerResumenIvaResponse403 | obtenerResumenIvaResponse404 | obtenerResumenIvaResponse422 | obtenerResumenIvaResponse429 | obtenerResumenIvaResponse500) & {
  headers: Headers;
};

export type obtenerResumenIvaResponse = (obtenerResumenIvaResponseSuccess | obtenerResumenIvaResponseError)

export const getObtenerResumenIvaUrl = (params: ObtenerResumenIvaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contabilidad/reportes/iva?${stringifiedParams}` : `/contabilidad/reportes/iva`
}

/**
 * Devuelve el resumen de IVA del mes: IVA débito fiscal e IVA crédito fiscal, cada uno desglosado por el origen del asiento (MANUAL, N8N, REVERSION), y la diferencia estimada entre ambos. Es un punto de partida para preparar la declaración de IVA, no la reemplaza (CLAUDE.md §10.5). Rol mínimo: auditor.
 * @summary Resumen de IVA mensual
 */
export const obtenerResumenIva = async (params: ObtenerResumenIvaParams, options?: Parameters<typeof clienteHttp>[1]): Promise<obtenerResumenIvaResponse> => {

  return clienteHttp<obtenerResumenIvaResponse>(getObtenerResumenIvaUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getObtenerResumenIvaQueryKey = (params?: ObtenerResumenIvaParams,) => {
    return [
    `/contabilidad/reportes/iva`, ...(params ? [params] : [])
    ] as const;
    }


export const getObtenerResumenIvaQueryOptions = <TData = Awaited<ReturnType<typeof obtenerResumenIva>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(params: ObtenerResumenIvaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenIva>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getObtenerResumenIvaQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof obtenerResumenIva>>> = ({ signal }) => obtenerResumenIva(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenIva>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ObtenerResumenIvaQueryResult = NonNullable<Awaited<ReturnType<typeof obtenerResumenIva>>>
export type ObtenerResumenIvaQueryError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useObtenerResumenIva<TData = Awaited<ReturnType<typeof obtenerResumenIva>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerResumenIvaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenIva>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerResumenIva>>,
          TError,
          Awaited<ReturnType<typeof obtenerResumenIva>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerResumenIva<TData = Awaited<ReturnType<typeof obtenerResumenIva>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerResumenIvaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenIva>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obtenerResumenIva>>,
          TError,
          Awaited<ReturnType<typeof obtenerResumenIva>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useObtenerResumenIva<TData = Awaited<ReturnType<typeof obtenerResumenIva>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerResumenIvaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenIva>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resumen de IVA mensual
 */

export function useObtenerResumenIva<TData = Awaited<ReturnType<typeof obtenerResumenIva>>, TError = SolicitudInvalidaResponse | NoAutenticadoResponse | ProhibidoResponse | NoEncontradoResponse | EntidadNoProcesableResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
 params: ObtenerResumenIvaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof obtenerResumenIva>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getObtenerResumenIvaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type diagnosticarMayorizacionResponse200 = {
  data: DiagnosticoMayorizacion
  status: 200
}

export type diagnosticarMayorizacionResponse401 = {
  data: NoAutenticadoResponse
  status: 401
}

export type diagnosticarMayorizacionResponse403 = {
  data: ProhibidoResponse
  status: 403
}

export type diagnosticarMayorizacionResponse429 = {
  data: DemasiadasPeticionesResponse
  status: 429
}

export type diagnosticarMayorizacionResponse500 = {
  data: ErrorInternoResponse
  status: 500
}

export type diagnosticarMayorizacionResponseSuccess = (diagnosticarMayorizacionResponse200) & {
  headers: Headers;
};
export type diagnosticarMayorizacionResponseError = (diagnosticarMayorizacionResponse401 | diagnosticarMayorizacionResponse403 | diagnosticarMayorizacionResponse429 | diagnosticarMayorizacionResponse500) & {
  headers: Headers;
};

export type diagnosticarMayorizacionResponse = (diagnosticarMayorizacionResponseSuccess | diagnosticarMayorizacionResponseError)

export const getDiagnosticarMayorizacionUrl = () => {




  return `/contabilidad/diagnostico/mayorizacion`
}

/**
 * Verifica, para toda cuenta, año y mes con movimiento, que saldo_cuenta_mensual sea igual a la suma de las líneas de asiento_linea (invariante de ADR-018), y lista las diferencias encontradas. Rol mínimo: contador, porque expone un diagnóstico técnico de la contabilización.
 * @summary Diagnóstico de mayorización
 */
export const diagnosticarMayorizacion = async ( options?: Parameters<typeof clienteHttp>[1]): Promise<diagnosticarMayorizacionResponse> => {

  return clienteHttp<diagnosticarMayorizacionResponse>(getDiagnosticarMayorizacionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDiagnosticarMayorizacionQueryKey = () => {
    return [
    `/contabilidad/diagnostico/mayorizacion`
    ] as const;
    }


export const getDiagnosticarMayorizacionQueryOptions = <TData = Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDiagnosticarMayorizacionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof diagnosticarMayorizacion>>> = ({ signal }) => diagnosticarMayorizacion({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DiagnosticarMayorizacionQueryResult = NonNullable<Awaited<ReturnType<typeof diagnosticarMayorizacion>>>
export type DiagnosticarMayorizacionQueryError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse


export function useDiagnosticarMayorizacion<TData = Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof diagnosticarMayorizacion>>,
          TError,
          Awaited<ReturnType<typeof diagnosticarMayorizacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiagnosticarMayorizacion<TData = Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof diagnosticarMayorizacion>>,
          TError,
          Awaited<ReturnType<typeof diagnosticarMayorizacion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiagnosticarMayorizacion<TData = Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Diagnóstico de mayorización
 */

export function useDiagnosticarMayorizacion<TData = Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError = NoAutenticadoResponse | ProhibidoResponse | DemasiadasPeticionesResponse | ErrorInternoResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diagnosticarMayorizacion>>, TError, TData>>, request?: SecondParameter<typeof clienteHttp>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDiagnosticarMayorizacionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






